### ISSUE TITLE
There is an error "The subscription... could not be found" in the subscription node after signing in with Azure China/Germany account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#122]
**OS:** Win 10
**Build Version:** 20220313.1

**Repro Steps:**

1. Sign in with Azure China/Germany account.
2. Expand the subscription node in Azure view.
3. Check whether there is no error in the subscription node.

**Expect:**
There is no error in the subscription node.

**Actual:**
There is an error "The subscription... could not be found" in the subscription node.
![image](https://user-images.githubusercontent.com/62053665/158147516-f3536568-73e7-4aaa-a7a9-63766e28e560.png)

**Comment by v-xinda** [comment]
@alexweininger  Verified this issue on the latest build 20220921.1, it doesn't reproduce for now. So I close it.
