### ISSUE TITLE
Implement `isTreeItem`: x is `TreeItem` to fix `instanceof` calls

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureresourcegroups#129]
Anywhere in the code base that uses `instanceof` for our top level tree items (SWA nodes, Function nodes, etc.) won't work anymore since technically the tree item being evaluated is the returned proxy tree item, which will be `instanceof AppResourceTreeItem` I think.  Should be easy enough to just implement `isTreeItem` on the resolved apps and convert any `instanceof` calls.

**Comment by alexweininger** [comment]
Closing this because it's sort of done/outdated.
