### ISSUE TITLE
[suggestion] Support Multiple AAD Accounts

### ISSUE THREAD

**Issue by simondmorias** [microsoft/vscode-azureresourcegroups#13]
Currently you can only sign in using one account. I would like to be able to sign in with many accounts cross tenants. 

Use case is that I work as a consultant across several clients at time.

**Comment by BigBearFreddy** [comment]
Agreed, support for multiple accounts and/or contexts would be much appreciated.

**Comment by EricJizbaMSFT** [comment]
That would be controlled by the Azure Account extension. Looks like they already have an issue here: https://github.com/microsoft/vscode-azure-account/issues/42

Thanks for the feedback and I would suggest adding your vote to that issue
