### ISSUE TITLE
Change `azureExtensions` list to use full ID of extensions, i.e. including publisher

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azureresourcegroups#158]
It's unlikely that future extensions created outside of our team would be published by `ms-azuretools`. We should alter the extension list in https://github.com/microsoft/vscode-azureresourcegroups/blob/main/src/azureExtensions.ts to use the full ID of the extension including publisher, so that it's possible for extensions outside of `ms-azuretools` to work.

**Comment by alexweininger** [comment]
There is an optional `publisher` property on the extensions that makes this possible already https://github.com/microsoft/vscode-azureresourcegroups/blob/d848af58a6a374f319103e87656278d8514fd10a/src/AzExtWrapper.ts#L41

**Comment by nturinski** [comment]
Don't we still need to manually update our manifest here though? https://github.com/microsoft/vscode-azureresourcegroups/blob/main/src/azureExtensions.ts

**Comment by alexweininger** [comment]
> Don't we still need to manually update our manifest here though? [https://github.com/microsoft/vscode-azureresourcegroups/blob/main/src/azureExtensions.ts](https://github.com/microsoft/vscode-azureresourcegroups/blob/main/src/azureExtensions.ts?rgh-link-date=2022-04-21T21%3A59%3A21Z)

Yeah, I think that's expected
