### ISSUE TITLE
Clicking on a storage account does not bring up it's properties

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureresourcegroups#166]
<img width="406" alt="Screen Shot 2022-04-13 at 1 14 12 PM" src="https://user-images.githubusercontent.com/22795803/163262831-066fb15e-6195-4e32-b68c-0abfbd7e48e1.png">

Clicking on other resource types brings up the properties. The types I tried: Microsoft.Insights/components, "Failure Anomalies", "Microsoft.Web/serverFarms"

I'm assuming this is because storage accounts will eventually have a drop-down that shows info from the storage extension but it's confusing that some nodes have a dropdown while others don't.

**Comment by wwlorey** [comment]
More info: I have the storage extension installed.

**Comment by alexweininger** [comment]
I think this was because the released version of the extension was installed, this is now fixed by #197
