### ISSUE TITLE
After installing extension when prompted, the prompt remains

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureresourcegroups#167]
<img width="406" alt="Screen Shot 2022-04-13 at 1 19 37 PM" src="https://user-images.githubusercontent.com/22795803/163263554-8a1d7285-82b7-4c37-ab30-0e1bcd4481bb.png">

I would expect this node to populate with the nodes pulled in from the app service extension after it's installed. If that's possible 🧐

**Comment by wwlorey** [comment]
More info: refreshing the app service node does not fill in child nodes. After reloading VS Code I get the same behavior as https://github.com/microsoft/vscode-azureresourcegroups/issues/166 but this time for the app service node

**Comment by alexweininger** [comment]
A lot of changes since this was filed, I can't repro and I think this any issue that was causing this has been fixed by #185.
