### ISSUE TITLE
I expected that grouping by location would still group by RGs, not individual resources

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureresourcegroups#170]
This could be a bad expectation on my part - but I'm thinking that seeing all the RGs in each location is more helpful than a flat list of resources. I'd be curious to see what customers would prefer.

<img width="237" alt="Screen Shot 2022-04-13 at 1 32 27 PM" src="https://user-images.githubusercontent.com/22795803/163265621-72e8693d-1508-42e9-b4b9-9d432708f4bf.png">

**Comment by bwateratmsft** [comment]
To do that would require a pretty significant change to how the grouping works, since it would mean conditionally adding a layer to the tree. I'd agree we should wait for customer feedback.

**Comment by MicroFish91** [comment]
Closing as not planned for now for same reasons above by Brandon
