### ISSUE TITLE
Changing grouping after deleting an item (e.g. SWA), causes that item to reappear in the tree

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azureresourcegroups#171]
Steps to reproduce:

1. Create a SWA
2. Delete it
3. Change the "Group By" setting
4. Browse to where that SWA would have been in the new grouping (had you not deleted it)
5. It's there!

According to @alexweininger we need to remove the `AppResource` from the cache, not just the `TreeItem`

**Comment by nturinski** [comment]
In a similar vein, whenever we add a tree item/app resource to the sub node, we'll need to make sure we add it to the cache otherwise we'll lose it when we change groupings.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/222/files
