### ISSUE TITLE
jsonc errors don't block editing tags

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#18]
**OS:** All
**Build Version:** 20200612.3
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one resource group -> Edit Tags... -> Add two tags with the same name in the tags.jsonc file.
![image](https://user-images.githubusercontent.com/45614674/84625064-1897d880-af15-11ea-86be-5ff7007c3115.png)
2. Ctrl+S.

**Expect:**
An error occurs.

**Actual:**
Prompt the below dialog to update tags for resource group. Click "Update", it will successfully updated tags for resource group.
![image](https://user-images.githubusercontent.com/45614674/84625447-d7ec8f00-af15-11ea-9877-14415a30483f.png)

**More Info:**
1. The updated tags only contain the final one of the two duplicate tags.
![image](https://user-images.githubusercontent.com/45614674/84625690-63feb680-af16-11ea-9cc2-c6746825ae07.png)
2. An error occurs when adding a duplicate tag in portal with the "Save" button disabled.
![image](https://user-images.githubusercontent.com/45614674/84624977-f56d2900-af14-11ea-97a3-0610040b9275.png)

**Comment by v-mengwe** [comment]
Verified on the latest build 20201216.1, this issue also reproduces for GitHub codesapces.
