### ISSUE TITLE
There is no "..." next to "Group by ARM Tag" action in the context menu and command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#183]
**OS:** All
**Build Version:** 20220418.9
**Regression:** Not a regression

**Repro Steps:**
1. Install "Resource Group" extension from VSIX.
2. Click "Group By".
3. Check whether there is a "..." next to "Group by ARM Tag" action in the context menu and command palette or not.

**Expect:**
There is a "..." next to "Group by ARM Tag" action in the context menu and command palette.

**Actual:**
There is no "..." next to "Group by ARM Tag" action in the context menu and command palette.
![image](https://user-images.githubusercontent.com/57662131/163943394-191697e3-06da-4822-bb61-b0ed1a3e2906.png)
![image](https://user-images.githubusercontent.com/57662131/163945537-9a150410-7b58-4b2a-bfb1-cda0e6fca275.png)

**Comment by bwateratmsft** [comment]
For "Group by ARM tag" in particular this makes sense, since there are prompts following it.

**Comment by alexweininger** [comment]
Fixed by a063194
