### ISSUE TITLE
Fail to execute command "Azure Resource Groups: Focus this Group" with an error from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#191]
**OS:** All
**Build Version:** 20220420.34
**Regression:** Not a regression

**Repro Steps:**

1. F1 -> Azure Resource Groups: Focus this Group.
2. Check whether succeeds to execute command "Azure Resource Groups: Focus this Group".

**Expect:**
Succeed to execute command "Azure Resource Groups: Focus this Group".

**Actual:**
Fail to execute command "Azure Resource Groups: Focus this Group" with an error.
<img width="446" alt="Screen Shot 2022-04-21 at 15 08 56" src="https://user-images.githubusercontent.com/62053665/164397795-4f152a5f-8aae-4615-9788-4222925eedfb.png">

**Comment by alexweininger** [comment]
Fixed by #200
