### ISSUE TITLE
The resource group cannot be multi-selected when executing command "Azure Resource Groups: Delete..." from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#193]
**OS:** All
**Build Version:** 20220420.34
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the Azure Resource extension groups by the resource group.
2. F1 -> Azure Resource Groups: Delete... -> Select a subscription.
3. Check whether the resource group can be multi-selected.

**Expect:**
The resource group can be multi-selected.
<img width="605" alt="Screen Shot 2022-04-21 at 16 43 39" src="https://user-images.githubusercontent.com/62053665/164416394-ab08e3c2-6355-4d29-ba54-8c53df30d1c2.png">

**Actual:**
The resource group cannot be multi-selected.
<img width="606" alt="Screen Shot 2022-04-21 at 16 44 10" src="https://user-images.githubusercontent.com/62053665/164416497-b03a25f2-6fa0-449b-9ca0-0b8caf297222.png">

**Comment by alexweininger** [comment]
Fixed by #198
