### ISSUE TITLE
Fail to execute command "Azure Resource Groups: Delete..." with an error from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#194]
**OS:** All
**Build Version:** 20220420.34
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the Azure Resource extension groups by the resource group.
2. F1 -> Azure Resource Groups: Delete... -> Select a subscription -> Select a resource group.
3. Check whether succeeds to execute command "Azure Resource Groups: Delete..."  directly.

**Expect:**
Succeed to execute command "Azure Resource Groups: Delete..." directly.

**Actual:**
Continue to perform the next step and fail to execute command "Azure Resource Groups: Delete..." with an error.
<img width="451" alt="Screen Shot 2022-04-21 at 16 46 57" src="https://user-images.githubusercontent.com/62053665/164416998-cfe37832-cfbd-4166-be47-c36a9a220bb1.png">

**More Info:**
Fail to execute command "Azure Resource Groups: Delete..." with the same error when grouping by other type.

**Comment by alexweininger** [comment]
Fixed by #198
