### ISSUE TITLE
It will fall back to the original .jsonc if don't save the second change for it

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#20]
**OS:** All
**Build Version:** 20200612.3
**Regression:** Not a Regression

**Repro Steps:**

1. Right click a resource group --> Select "Edit tags…". 
2. Pop up a .jsonc file, change this tags like:
 {
     "<Insert tag name>": "test1"
 }
10. Ctrl+F4 --> Pop up a prompt --> Click "Save".
11. Select "Edit tags…" again.
12. Check the tags has saved successfully.
13. Change this tags like: 
{
     "<Insert tag name>": "test2"
}
21. Ctrl+F4 --> Pop up a prompt --> Click " Don't Save".
22. Select "Edit tags…" again.
23. Check the tags.

**Expect:**
It shows the edited tags, like:
 {
     "<Insert tag name>": "test1"
 }

**Actual:**
It shows the original tags, like: 
{
    "<Insert tag name>": "<Insert tag value>"
}

**Comment by EricJizbaMSFT** [comment]
@v-mengwe I see an error if I try to save with your content in step 2 because angle brackets are not allowed. If I remove the angle brackets, it works as expected

**Comment by v-mengwe** [comment]
@EricJizbaMSFT Yes, I saw the error. But I can save the first change successfully with this error in step2. I'm not sure if this behavior is expected.

If it is expected, then continue following my repro steps, the final result will be keep my first saving in step2 instead of the original one after not saving the second change(step7).

If it is not expected, that means I can't save the first change with the error. But I can, this is another issue.

Hope this can clarify my issue.

**Comment by EricJizbaMSFT** [comment]
> But I can save the first change successfully with this error in step2. I'm not sure if this behavior is expected.

It's a known issue. Added more description here, which we will use for tracking: https://github.com/microsoft/vscode-azureresourcegroups/issues/19. You say you can save the change "successfully", but that's only because the file in VS Code looks like it saved, right? If you check the tags in the portal, I'm guessing you will _not_ see any changes to the tags there.
