### ISSUE TITLE
There is no response after clicking "Click to view resource" in "Activity Log"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#202]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Previous Build

**Repro Steps:**
1. Make sure the Azure Resources group by the **Resource Group**.
2. Create a Function App.
3. Click "Click to view resource" in "Activity Log".
4. Check whether the created Function App is focused or not.

**Expect:**
The created Function App is focused.

**Actual:**
There is no response after clicking "Click to view resource".

**More Info:**
This issue does not reproduce on the previous unified Azure Resource extension build 20220420.34.

**Comment by alexweininger** [comment]
@nturinski Did something change with how app resource tree item ids are created? The reveal isn't working at all anymore

**Comment by v-ruizh** [comment]
Verified this issue on the extension 20220524.1, it has been fixed.
