### ISSUE TITLE
An error occurs when executing "Edit Tags..." action for a Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#203]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Previous Build

**Repro Steps:**
1. Create a Function App.
2. Right click this Function App and execute "Edit Tags..." action.
3. Check whether the "xxx-tags.jsonc" file opens or not.

**Expect:**
The "xxx-tags.jsonc" file opens.
![image](https://user-images.githubusercontent.com/45614674/164605209-7ae5ada1-a5fc-43db-8c34-b9f2a104aed5.png)

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/164605293-f3866791-2039-44f4-81b6-55470d1f3a8a.png)

**More Info:**
This issue does not reproduce on the Azure Resource extension previous unified build 20220420.34.

**Comment by nturinski** [comment]
Note to self: This only reproduces for Function Apps.  Very likely related to the fact that we change the provider id to `functionapp` from `sites`.
