### ISSUE TITLE
The dialog message is inconsistent when deleting a VM resource group with different status

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#210]
**OS:** All
**Azure Resource Extension Build Version:** 20220427.11 (unified)
**Azure VM Extension Build Version:** 20220426.1 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the resource group by Resource Group.
2. Right click a VM resource group -> Delete -> Pop up a dialog 1 -> Cancel.
3. Expand the VM resource group -> Click "Showing * of * resources..." to show all resources -> Right click the VM resource group -> Delete -> Pop up a dialog 2.
4. Check whether the dialog message of the dialog 1 and dialog 2 is consistent.

**Expect:**
The dialog message of the dialog 1 and dialog 2 is consistent.

**Actual:**
The dialog message of the dialog 1 and dialog 2 is inconsistent.
<img width="261" alt="Screen Shot 2022-04-28 at 17 47 03" src="https://user-images.githubusercontent.com/62053665/165725961-98638e8f-6154-49b5-9d0c-9a24bf9b91fc.png">
<img width="266" alt="Screen Shot 2022-04-28 at 17 32 03" src="https://user-images.githubusercontent.com/62053665/165725988-96404aa5-810b-42a5-b1b9-83fa276a404e.png">

**Suggestion:**
Regardless of whether the resource group is "shown" or "hidden", it would be better to show all resources in the dialog message when deleting it.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/311
