### ISSUE TITLE
Item naming in the "Create Resource..." quickpick needs reworking

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureresourcegroups#214]
The names of options we have for creating resources are confusing (specifically the boxed ones below). It's unclear which option to go with unless you're an Azure pro.

![image](https://user-images.githubusercontent.com/22795803/166324824-815994df-6417-497d-9a62-750b6effae96.png)

@fiveisprime suggested we add a [detail](https://code.visualstudio.com/api/references/vscode-api#QuickPickItem) to each quickpick as well as the service name. Something like this:

```
| Create Static Web App
| > Host your front-end apps.
---
| Create App Service Web App
| > Host your APIs and full stack apps.
```

**Comment by fiveisprime** [comment]
The `Create Server` needs to be updated to `Create Database Server` so it actually makes sense 🤣

```
| Create Static Web App...
| > For front-end apps with optional serverless back-ends.
---
| Create App Service Web App...
| > For APIs and full stack apps.
---
| Create Function App in Azure...
| > For serverless, event driven apps and automation.
---
| Create Database Server...
| > SQL or NoSQL databases for your web apps.
---
| Create Virtual Machine...
| > For any workload or a remote dev box.
---
| Create Resource Group...
| > The logical grouping for your resources.
```

**Comment by alexweininger** [comment]
From Matt offline:

```
| Create Storage Account...
| > For file storage and static file hosting.
---
| Create Container App...
| > For Microservices using serverless containers.
```
