### ISSUE TITLE
The resource always groups by Resource Type when editing tags from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#224]
**OS:** All
**Azure Resource Extension Build Version:** 20220505.12(unified)
**Regression:** Not a regression

**Repro Steps:**
1. Make sure the resource groups by Resource Group.
2. F1 -> Click "Azure Resource Groups: Edit Tags...".
3. Check whether the resource groups by Resource Group.

**Expect:**
The resource groups by Resource Group.

**Actual:**
The resource always groups by Resource Type.
![image](https://user-images.githubusercontent.com/57662131/167059252-82679138-ba43-417f-8b6e-8f7723118a01.png)

**More Info:**
1. This issue also reproduces when the resource groups by Location/ARM Tag.
2. This issue also reproduces when executing command "Azure Resource Groups: Open in Portal" and "Azure Resource Groups: View properties" from command palette.

**Comment by bwateratmsft** [comment]
I think this is by-design but I'll let @alexweininger or @nturinski confirm.

**Comment by nturinski** [comment]
This is currently by-design.  Typically, it's easier to find a resource that you are looking for by the type rather than the group.  I don't think we currently have any plans to change this unless we find that users really want the tree picker to be grouped by the current `groupBy` setting.
