### ISSUE TITLE
The icon is incorrect and the tooltip is "Focus this Group" after focusing a group on M1

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#225]
**OS:** M1
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Regression:** 20220503.22

**Repro Steps:**

1. Click the "Focus this Group" icon to focus a group -> Mouse over to the icon.
2. Check whether the icon is correct and the tooltip is "Unfocus Group" or not.

**Expect:**
The icon is correct and the tooltip is "Unfocus Group".
<img width="416" alt="Screen Shot 2022-05-06 at 16 31 27" src="https://user-images.githubusercontent.com/62053665/167097944-2ad37138-e61f-4c36-a6d0-dd5be2e28506.png">

**Actual:**
The icon is incorrect and the tooltip is "Focus this Group".
<img width="346" alt="Screen Shot 2022-05-06 at 16 39 41" src="https://user-images.githubusercontent.com/62053665/167097956-5eb9f78f-7866-4989-9c0a-360c44c6f015.png">

**More Info:**
This issue does not reproduce on Linux/Windows OS.

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/236
