### ISSUE TITLE
Focus/unfocus waits for all expanded app resources to re-resolve

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#232]
I'm guessing this is an unfortunate side effect of https://github.com/microsoft/vscode-azureresourcegroups/pull/227 or #222 

https://user-images.githubusercontent.com/12476526/167915313-959a555c-ddf3-4689-86b4-f1149547d692.mov

**Comment by bwateratmsft** [comment]
I'm not having luck reproducing:
![Recording 2022-05-11 at 14 08 37](https://user-images.githubusercontent.com/36966225/167917305-bd4a2b60-3492-4c2b-ba4c-afcbd286f1a3.gif)

**Comment by alexweininger** [comment]
I can no longer reproduce this lol... 🎉
