### ISSUE TITLE
[Suggestion] It would be better if the resources arrange alphabetically when selecting a storage account resource 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#237]
**OS:** All
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Azure Storage Extension Build Version:** 20220505.2 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. F1 -> Azure Storage: Create Table -> Select a subscription.
2. Check whether the resources arrangement is friendly or not.

**Actual:**
The resources arrangement is not friendly.
<img width="364" alt="Screen Shot 2022-05-07 at 15 51 37" src="https://user-images.githubusercontent.com/62053665/167244707-0951c166-e0bc-4794-8d5c-854e59be9876.png">

**Suggestion:**
It would be better if the resources arrange alphabetically.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/312
