### ISSUE TITLE
The tag shows the original tag after refreshing 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#252]
**OS:** Win10
**Build Version:** 20220515.1
**Regression:** Not a Regression

**Repro Steps:**

1. Make sure the resource groups by Resource Group/Location/ARM Tag.
2. Right click a resource group -> Edit Tags... -> Edit the tag in the opened file as below -> Save and update.
    ![image](https://user-images.githubusercontent.com/62053665/168562828-9433a2bd-f6ea-4554-b9f0-1512ebb52a8f.png)
3. Refresh the resource group.
4. Check whether the tag is updated in the opened file.

**Expect:**
The tag is updated in the opened file, like below:
![image](https://user-images.githubusercontent.com/62053665/168562864-b492baf5-2b71-43c6-af34-25d9fbe47f4a.png)

**Actual:**
The tag shows the original tag, like below:
![image](https://user-images.githubusercontent.com/62053665/168563050-fb5f4fc2-daee-4ccb-b797-ba3b0281ede6.png)

**More Info:**
Restart VS Code can fix this issue.

**Comment by v-mengwe** [comment]
Verified on the latest build 20220523.7, this issue still reproduces for now, so reopen it.

**Repro Steps:**

1. Right click a resource group -> Edit Tags... -> Edit the tag in the opened file as below -> Save and update.
2. Close the opened .jsonc file -> Refresh -> Right click the resource group -> Edit Tags again.

**Actual:**
The tag shows the original tag.

**More Info:**
Restart VS Code can fix this issue.

**Comment by alexweininger** [comment]
It works if you use this new refresh button.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/12476526/182726649-ccfff3c6-52e3-46ab-bb61-22d596889259.png">
