### ISSUE TITLE
The tag isn't updated in the opened file when viewing properties for a resource

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#253]
**OS:** Win10
**Build Version:** 20220515.1
**Static Web App Extension Build Version:** 20220513.11
**Regression:** Not a Regression

**Repro Steps:**

1. Make sure the resource groups by Resource Type.
2. Right click a Static Web App -> Edit Tags... -> Edit the tag in the opened file as below -> Save and update.
    ![image](https://user-images.githubusercontent.com/62053665/168562828-9433a2bd-f6ea-4554-b9f0-1512ebb52a8f.png)
3. Refresh the resource group -> The tag is updated in the opened file.
4. Right click a Static Web App -> View Properties.
5. Check whether the tag is updated in the opened file.

**Expect:**
The tag is updated in the opened file.
![image](https://user-images.githubusercontent.com/62053665/168565036-af9e42ab-77b5-461d-8c9c-bf89b4bfaea3.png)

**Actual:**
The tag isn't updated in the opened file.
![image](https://user-images.githubusercontent.com/62053665/168565023-912eb3bf-e316-474b-9d22-6f1af512cc30.png)

**More Info:**
Restart VS Code can fix this issue.

**Comment by alexweininger** [comment]
Fiex by #461
