### ISSUE TITLE
The child node under the "Workflow" is not refreshed after right clicking a subscription or clicking "Refresh" button to refresh

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#254]
**OS:** Win10
**Build Version:** 20220515.1
**Static Web App Extension Build Version:** 20220513.11
**Regression:** Not a regression

**Repro Steps:**

1. Expand a static web app -> Production -> Workflow -> Click a child node -> Edit the config value in the opened .yml file.
2. Right click the subscription/Click the "Refresh" button in the "RESOURCES" node bar -> Refresh.
3. Check whether the child node under the "Workflow" is refreshed.

**Expect:**
The child node under the "Workflow" is refreshed.

**Actual:**
The child node under the "Workflow" is not refreshed.

**More Info:**
This issue doesn't reproduce when refreshing the "Static Web Apps" node.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/339
