### ISSUE TITLE
There is no response after clicking the "Refresh" action in the context menu of resource group

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#263]
**OS:** Win10
**Build Version:** 20220516.8
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the resource groups by Resource Group -> Right click a resource group -> Refresh.
2. Check whether succeeds to execute the "Refresh" action.

**Expect:**
Succeed to execute the "Refresh" action.

**Actual:**
There is no response after clicking the "Refresh" action.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/339
