### ISSUE TITLE
[Unstable] An error occurs when expanding a resource group

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#264]
**OS:** Win10
**Build Version:** 20220516.8
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the resource groups by Resource Group -> Expand a resource group.
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/62053665/168799288-4aae07dc-e846-4876-acfc-b1840dff1e24.png)

**More Info:**
This error pops up irregularly and the frequency is chaotic.

**Comment by alexweininger** [comment]
I've seen this very rarely with SWA and Web Apps. Seems hard to reproduce.

**Comment by alexweininger** [comment]
We've seen reports of this also happening if a group is focused before it is expanded.

**Comment by alexweininger** [comment]
Created https://github.com/microsoft/vscode-azureresourcegroups/issues/284 because although it's the same error message, it's likely a different bug than this one.

**Comment by alexweininger** [comment]
The only way I've been able to reproduce this is with these steps:
1. Focus on a resource group
2. Unfocus resource group
3. Go and expand other resource groups
