### ISSUE TITLE
[Unstable] An error occurs after refreshing the "Workspace" view

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#270]
**OS:** Win10
**Azure Resource Extension Build Version:** 20220518.13
**Azure Storage Extension build Version:** 20220518.1

**Repro Steps:**

1. Install the Resources extension in VS Code.
2. Install the Storage extension in VS Code.
3. Expand the "Workspace" view -> Click "Refresh" icon.
4. Check whether no error pops up.

**Expect:**
No error occurs.

**Actual:**
1. An error occurs.
    ![image](https://user-images.githubusercontent.com/62053665/169026317-18591548-021c-4350-af9d-8e1c0b14d3a5.png)
2. Nothing show under the "Workspace" view.
    ![image](https://user-images.githubusercontent.com/62053665/169026482-848d7d7d-6115-4859-ab78-c6dbc8618671.png)

**More Info:**
This issue does not reproduce if only installing the Resources extension in VS Code.

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-cosmosdb/pull/2024 and https://github.com/microsoft/vscode-azurestorage/pull/1061
