### ISSUE TITLE
The created resource group does not exist in the list when editing tags from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#273]
**OS:** Win10
**Build Version:** 20220519.11
**Regression:** Not a regression

**Repro Steps:**

1. Create a new resource group.
2. F1 -> Azure: Edit Tags -> Select a subscription.
3. Check whether the created resource group in the list.

**Expect:**
The created resource group in the list.

**Actual:**
The created resource group does not in exist the list.
![image](https://user-images.githubusercontent.com/62053665/169459849-4c8d1e25-beea-4eb1-92c8-38f04d8b1565.png)

**More Info:**

1. This issue also reproduces for commands "**Azure: View Properties/Open in Portal**" from command palette.
2. This issue doesn't reproduce for command "**Azure: Delete Resource Group**" from command palette.

**Comment by v-ruizh** [comment]
Can't execute commands "Azure: Edit Tags/View Properties/Open in Portal" for resource group by Command Palette. There is no resource "Resource Group" in the resource list when executing commands "Azure: Edit Tags/View Properties/Open in Portal".
![image](https://user-images.githubusercontent.com/45614674/172798318-d448d19b-301f-42df-9cdc-808555e1ee22.png)

**Comment by alexweininger** [comment]
This is accessible from a resource group context menu. We'll re-open this if users want this.
