### ISSUE TITLE
Resources view does not auto-refresh when deleting an expanded resource group

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#275]
**OS:** Win10
**Build Version:** 20220519.11

**Repro Steps:**
1. Expand a resource group which has resources in it.
2. F1 -> Azure: Delete Resource Group... -> Select the above resource group to delete it.
3. Check whether the resource group is removed from the resource list or not.

**Expect:**
The resource group is removed from the resource list.

**Actual:**
The resource group still exists in the resource list.

**More Info:**
1. This issue does not reproduce if the resource group is collapsed.
2. This issue reproduces no matter what the resources groups by.

**Comment by alexweininger** [comment]
If the currently focused resource group is deleted, we should reset the focus state.

**Comment by alexweininger** [comment]
This has been fixed by v2

**Comment by v-ruizh** [comment]
This issue does not reproduce on the resource groups extension 20230405.7.
