### ISSUE TITLE
The resource group of the new VM/Storage account doesn't show in the list when deleting the resource group

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#281]
**OS:** Win10/M1
**Azure Resource Extension Build Version:** 20220523.7

**Repro Steps:**
1. Make sure the resource groups by "Resource Type".
2. Create a VM/Storage account.
3. F1 -> Azure: Delete Resource Group.
4. Check whether the resource group of the new VM/Storage account shows in the list.

**Expect:**
The resource group of the new VM/Storage account shows in the list.

**Actual:**
The resource group of the new VM/Storage account doesn't show in the list.

**More Info:**
This issue does not reproduce for App Service and Function App.

**Comment by alexweininger** [comment]
Fixed by v2

**Comment by v-ruizh** [comment]
This issue does not reproduce on the resource groups extension build 20230405.7.
