### ISSUE TITLE
The new created resource group disappears after clicking "Focus this Group" for it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#286]
**OS:** Win10/M1
**Build Version:** 20220525.12
**Regression:** Not a regression

**Repro Steps:**
1. Make sure the resource groups by Resource Group.
2. Create a resource group and click "Focus this Group" for it.
3. Check whether the new created resource group is focused or not.

**Expect:**
The new created resource group is focused after clicking "Focus this Group" for it.

**Actual:**
The new created resource group disappears after clicking "Focus this Group" for it.
![actual2](https://user-images.githubusercontent.com/45614674/170449245-baa3da6a-fa87-4539-acc1-515b7f8f03dc.gif)

**More Info:**
1. Refresh the resources view, the new created resource group is focused.
2. This issue also reproduces on the latest released resource group extension.

**Comment by alexweininger** [comment]
Caused by #285
