### ISSUE TITLE
The deleted resource group shows in the list when executing "Azure: Delete Resource Group..." from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#287]
**OS:** All
**Azure Resource Extension Build Version:** 20220525.7

**Repro Steps:**
1. Delete a resource group.
2. F1 -> Azure: Delete Resource Group.
3. Check whether the deleted resource group doesn't show in the list.

**Expect:**
The deleted resource group doesn't show in the list.

**Actual:**
The deleted resource group shows in the list.
![image](https://user-images.githubusercontent.com/57662131/170460346-11b3972d-6ae8-4c26-948d-6741f9d63e8d.png)

**More Info:**
Refresh can fix this issue.

**Comment by alexweininger** [comment]
Duplicate of #355
