### ISSUE TITLE
Can't reveal the storage account in Storage explorer even though the Azure Storage extension installed

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#3]
**OS:** All
**Build Version:** [20200310.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16104&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Expand one resource group->click one storage account->Install the Azure Storage extension.
2. Click this storage account again.

**Expect:**
It should reveal this storage account in Storage explorer.

**Actual:**
Open a .json file.
![image](https://user-images.githubusercontent.com/45614674/76391632-dc4f5c00-63aa-11ea-85fc-c040828d8938.png)

**More Info:**
This issue does not reproduce for web app and function app.

**Comment by EricJizbaMSFT** [comment]
This should work if you install the latest build of Storage from Azure Dev Ops. It'll be included in the v0.9.0 release coming soon
