### ISSUE TITLE
[Suggestion] Add a "View Output" button in the notification after creating a resource group

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#31]
**OS:** Windows 10
**Build Version:** 20200728.1

**Repro Steps:**
1. Create a resource group in VS Code.
2. Check the notification.

**Actual:**
There is no "View Output" button in the notification.
![image](https://user-images.githubusercontent.com/45614674/88782773-901d8080-d1c0-11ea-8395-2f76bf4e8b08.png)

**Suggestion:**
Add a "View Output" button in the notification.

**Comment by EricJizbaMSFT** [comment]
We only direct users to the output window when there's additional helpful info that doesn't fit well in a notification. For this scenario, a notification tells you all you need to know
