### ISSUE TITLE
Not able to use the extension when I already authenticated and later I used a azure sandbox.

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode-azureresourcegroups#324]
Authenticate with a user in which you don't have any subscription and later go to microsoft.com/learn and create an app sandbox for example this one https://docs.microsoft.com/en-us/learn/modules/host-a-web-app-with-azure-app-service/3-exercise-create-a-web-app-in-the-azure-portal?pivots=csharp
Now you have no way to authenticate the subscription. 

This is a broken functionality that I can't reconnect. I am not able to use my Sandbox. Let me know if there is a workaround regarding this issue. I believe there must be a button which let me connect again so I can use the subscription which temporary provided to my account.

**Comment by alexweininger** [comment]
Signing out with the "Azure: Sign Out" via the command palette (F1) and then signing back in again should make the newly created subscription appear.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/12476526/177654024-8b9d00e7-c0a5-4c3b-b269-de524e93b469.png">

**Comment by alexweininger** [comment]
Side note: the refresh button should take care of this if it isn't already

**Comment by anirugu** [comment]
I try to sign out and it's started showing the subscription. @alexweininger The Sandbox Subscription is added temporarily for practice so it doesn't get updated by the refresh button.

**Comment by nturinski** [comment]
@anirugu But signing out and back in did resolve the issue?

**Comment by anirugu** [comment]
Yes
