### ISSUE TITLE
The "Group By" icon disappears from the resources view after installing both Azure Function extension and App Service extension

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#330]
`azureResourceGroups.groupBy` and `azureWorkspaceCreate` submenus are missing on Insiders `1.70.0-insider`. It works on `1.66.1` (stable).

When debugging we get these errors:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/12476526/178556572-ab9530ee-f144-462c-b934-42c15f23918d.png">

Errors don't make much sense to me since they are defined in the submenus section of the RGs package.json.

![image](https://user-images.githubusercontent.com/12476526/178571651-d2ded0ec-5f91-4c94-8b11-2a96364ce67a.png)

### Broken version info:

Version: 1.70.0-insider
Commit: f3528d481b366b24321c382d5e5849f4c7d65248
Date: 2022-07-12T09:33:59.420Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

### Working version info:

Version: 1.66.1 (Universal)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:49:47.400Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.5.0

**Comment by alexweininger** [comment]
@fiveisprime this is the issue you encountered yesterday. A fix is merged but unreleased.

https://github.com/microsoft/vscode/issues/155030

**Comment by alexweininger** [comment]
@isidorn this issue has been in insiders for a while now, and still isn't fixed. It would be great to get fixed before the July stable release.

**Comment by isidorn** [comment]
@alexweininger sorry about that but we are releasing July stable today. So this will not be fixed for the July stable release. Also Joh is now on vacation. 
I can assign that issue to August but it would be good if you can investigate this a bit more from your side.

Also I see that you say that it works in 1.66, how about in 1.69? Or even better can you find the exact insiders version when this broke.

**Comment by alexweininger** [comment]
> Also I see that you say that it works in 1.66, how about in 1.69? Or even better can you find the exact insiders version when this broke.

@isidorn it works in `1.69.1`. 

I'm not sure how to find the exact insiders version where it broke, but I'm pretty sure it is caused by https://github.com/microsoft/vscode/pull/154801/commits/21147b8c9827809b5dc7db1236b0ff8ccf6c1cd2.

**Comment by isidorn** [comment]
@alexweininger thanks a lot. I was discussing with @fiveisprime and the earliest we can do a recovery release is Wednesday next week, before that Joh is back from vacation and will investigate the issue and potentially revert that commit if that is the cause.

**Comment by alexweininger** [comment]
Fixed in https://github.com/microsoft/vscode/releases/tag/1.70.2
