### ISSUE TITLE
An error “Resource group could not be found” occurs for the resource group after deleting it

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#34]
**OS:** Mac/Windows
**Build:** 20200803.1

**Repro Steps:**
1. Right click a resource group --> Click "Delete...".
2. Refresh --> Check the result. 
3. Delete successfully --> Check the result.

**Expect:**
Disappear from the "Resource Groups" list.

**Actual:**
There is an error "Resource group could not be found".
![image](https://user-images.githubusercontent.com/57662131/89268436-1e837d80-d66b-11ea-96fb-ad30c4b87c3b.png)

**More Info:**
This issue can be fixed after clicking "Refresh" button.

**Comment by EricJizbaMSFT** [comment]
This is a timing issue coming from Azure. It should go away eventually and we don't have much control here.
