### ISSUE TITLE
Change the minimum VS Code version that the Azure Resources extension supports

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#343]
**OS:** Win10
**Build Version:** 20220722.9

**Repro Steps:**
1. Figure out the oldest vs code version that the Azure Resources extension supports, the version is **1.57.0**.
2. Install VS Code **1.57.1** from https://code.visualstudio.com/updates.
3. Install the Azure Resources extension.
4. Expand the subscription node in Azure view.
5. Check whether there is no error in subscription node.

**Expect:**
There is no error in subscription node.

**Actual:**
An error occurs in subscription node.
![image](https://user-images.githubusercontent.com/45614674/180715920-371e76f1-fdde-42a8-95d6-6c09c43e7142.png)

**Comment by alexweininger** [comment]
Since the minimum version for some extensions is `1.66.0`, we should just require that. 

https://github.com/microsoft/vscode-azurefunctions/blob/main/package.json#L10
