### ISSUE TITLE
[Suggestion] It would be better to add the "Open Azure Extensions Walkthrough" command in the command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#344]
**OS:** All
**Build Version:** 20220722.9
**Regression:** Not a regression

**Repro Steps:**
1. F1.  
2. Check whether there is a "Open Azure Extensions Walkthrough" command the command palette.

**Actual:**
There is no "Open Azure Extensions Walkthrough" command in the command palette.

**Suggestion:**
It would be better to add the "Open Azure Extensions Walkthrough" command in the command palette.

**Comment by alexweininger** [comment]
It doesn't seem that other extensions are contributing commands for opening their walkthroughs. To open the walkthrough via the command palette, users can use the `"Get Started: Open Walkthrough..."` command.
