### ISSUE TITLE
Resources still show up on QuickPick list after being deleted

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureresourcegroups#355]
1. Delete some resources
2. Run a command via command palette
3. The deleted resources still show up in quickpicks

![image](https://user-images.githubusercontent.com/5290572/182497948-8cb28421-9a5a-4e02-a512-5bd2b3e83b6a.png)

I assume that this is happening because while the resources are deleted from the SubTree, they still are in the AppResources until a refresh happens.

**Comment by alexweininger** [comment]
Fixed in v2
