### ISSUE TITLE
Fail to create resource using `view/title` button

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#363]
Currently reproduces on 1.71.0-insider, caused by https://github.com/microsoft/vscode/pull/157803

Repro steps:

1. Click "Create Resource" from the `view/title`. 
1. Select any option (Function App for example)

https://user-images.githubusercontent.com/12476526/185259811-0c76adb8-e946-4e91-9ccb-c7210e28d583.mov

**Comment by alexweininger** [comment]
Release of the feature that causes this bug is being delayed until September https://github.com/microsoft/vscode/issues/42903#issuecomment-1225956482

I don't think this feature will break any other commands, it only impacts commands that are invoked via a view/title button. Currently the only commands we have for view/title are Create Resource, and Refresh.

**Comment by alexweininger** [comment]
So seems like the new way they implemented it no longer breaks the commands.

**Comment by nturinski** [comment]
Yep, confirms that it seems fine for me too, but should probably investigate what's really getting passed back.

**Comment by alexweininger** [comment]
investigation update...

The callback is passed two arguments, 1. the focused tree item, and then 2. an array of the selected tree items.

The focused tree item argument does replace our subscription argument, however, since each node has access to the subscription, it works all the same. We will have to plan for this for v2.

This does change the UX slightly. For example, if the user has two subscriptions shown previously we'd prompt them to pick a subscription. However, if the user has a node focused, the subscription that node is under will be auto picked.

**Comment by alexweininger** [comment]
Fixed by a PR a while ago...
