### ISSUE TITLE
The folder containing100 files is not completely deleted in once for a blob container

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#376]
**OS:** Win10
**Build Version:** 20220908.8

**Repro Steps:**

1. Install Azure Resource Groups extension.
2. Install Azure Storage extension.
3. Make sure resource groups by Resource Type.
4. Expand a storage account -> Create a new blob container -> Upload a folder containing 100 files to it.
5. Delete the folder -> Refresh.
6. Check whether the folder is completely deleted without any error.

**Expect:**
The folder is completely deleted without any error.

**Actual:**
The folder is not completely deleted with an error.
![test1](https://user-images.githubusercontent.com/107091828/189311821-9338e94d-d414-4f05-8866-f83d7cd06113.gif)

**More Info:**
There is an error under file share after deleting the uploaded folder containing 100 files, refreshing the file share can fix this issue.
![image](https://user-images.githubusercontent.com/107091828/189312205-79bd35a3-3380-4936-b678-f394cbe7b982.png)

**Comment by nturinski** [comment]
Should be fixed by https://github.com/microsoft/vscode-azurestorage/commit/c3845e61cfdd63bb325e1f50884914871ff23a64. Could you verify please?

**Comment by v-chenzha** [comment]
@nturinski Verified this issue on the latest build 20220925.1, it doesn't reproduce for now.
