### ISSUE TITLE
Succeed to create an empty blob to blob container with an error

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#377]
**OS:** Win10
**Build Version:** 20220908.8

**Repro Steps:**

1. Install Azure Resource Groups extension.
2. Install Azure Storage extension.
3. Make sure resource groups by Resource Type.
4. Expand a storage account -> Create a new blob container -> Right click the blob container -> Select "Create Empty Blob"
5. Check whether succeeds to create an empty blob without any error.

**Expect:**
Succeed to create an empty blob without any error.

**Actual:**
Succeed to create an empty blob with an error.
![image](https://user-images.githubusercontent.com/107091828/189316807-646189ef-27c8-406a-92d6-8056e8cd2565.png)

**More Info:**
1. This issue also reproduces when creating an empty file to file share.
2. This issue also reproduces when opening an uploaded file for file share or blob container.
3. This issue doesn't reproduce on the previous released Azure Resources extension.

**Comment by nturinski** [comment]
Unfortunately this will produce on the release version of storage, so we might want to sim-ship Storage, RG, and Container Apps all together 😬

**Comment by alexweininger** [comment]
<img src="https://media2.giphy.com/media/YVvTCqTBglkOs/giphy.gif"/>
