### ISSUE TITLE
Error when creating resource group

### ISSUE THREAD

**Issue by amyetman** [microsoft/vscode-azureresourcegroups#400]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureResourceGroups.createResourceGroup
Error type: TypeError
Error Message: Cannot read property 'Separator' of undefined

Version: 0.5.4
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

<details>
<summary>Call Stack</summary>

```
getGroupedPicks extension.bundle.js:2:738885
extension.bundle.js:2:738992extension.bundle.js:2:738992
fulfilled extension.bundle.js:2:736362
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by nturinski** [comment]
Could you provide repro steps please?

**Comment by MicroFish91** [comment]
Closing as stale, please feel free to re-open if you're still encountering this issue.
