### ISSUE TITLE
Update minimum VS Code engine

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#403]
**OS:** Win10
**Build Version:** 20221013.1
**VS Code Version:** 1.65.2

**Repro Steps:**

1. Figure out the oldest vs code version that the Azure Resources extension supports, the version is 1.65.0.
2. Install VS Code 1.65.2 from https://code.visualstudio.com/updates.
3. Install the Azure Resources extension.
4. Create a resource group.
5. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/195816218-ddd37dde-a51c-495f-a9c3-9cf9774f267c.png)

**Comment by alexweininger** [comment]
Need to update our minimum required version of VS Code in the package.json
