### ISSUE TITLE
Distinguish uppercase and lowercase letters when deleting the resource group

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#42]
**OS:** All
**Build Version:** 20200927.1

**Repro Steps:**

1. Create a resource group with name "TEST".
2. Right click the "TEST' resource group --> Select "Delete.." --> Enter "test" to delete this resource group.
3. Check the result.

**Expect:**
Succeed to delete this resource group by entering "test".

**Actual:**
There is an error when entering "test" to delete this resource group.
![image](https://user-images.githubusercontent.com/62053665/94412726-b786ce80-01ac-11eb-8f32-146ff6dd90f2.png)

**More Info:**

1. Succeed to delete this resource group by entering "test" in portal.
   ![image](https://user-images.githubusercontent.com/62053665/94416007-e010c780-01b0-11eb-8505-857feeb7af4d.png)
2. There is an error when creating a resource group with name "test" after step 1.(Uppercase and lowercase letters are not distinguished when creating the resource group.)
   ![image](https://user-images.githubusercontent.com/62053665/94415246-ece0eb80-01af-11eb-8a7b-a6fe64efb213.png)

**Comment by EricJizbaMSFT** [comment]
Let's match the portal
