### ISSUE TITLE
[Suggestion] Change the notification to "The Process was exist..." when deleting a resource group again

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#43]
**OS:** Win10
**Build Version:** 20201013.1

**Repro Steps:**
1. Right click the resource group -->Click "Delete...". 
2. Delete it again during the resource group is deleting.
3. Check the result.

**Actual:**
Pop up the notification "Started delete of resource group..." again.
![image](https://user-images.githubusercontent.com/57662131/95970520-a1327100-0e42-11eb-9a82-b833ae12436e.png)

**Suggestion:**
Pop up the notification "The Process was exist...".

**Comment by ejizba** [comment]
The technical cost of checking if the resource group is currently deleting isn't worth the benefit of a slightly better message in this case
