### ISSUE TITLE
Rename repository to "vscode-azureresources" to reflect updated extension name

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#452]
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

Process is easy and all old urls will automatically redirect to the new repository url, including git commands.

**Comment by bwateratmsft** [comment]
Neat. Will things like creating GitHub issues via the Report Issue command still work, when executed from an older extension version that doesn't have the updated issues repository?

**Comment by alexweininger** [comment]
After some discussion we decided to not do this.
