### ISSUE TITLE
An error occurs when creating a resource group from Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#466]
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
F1 -> Azure: Create Resource Group...

**Expect:**
It navigates to next step without any error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/209345911-b9049874-884c-4b65-87eb-6ff7bc7988d4.png)

**More Info:**
1. This issue also reproduces when creating resource group with "Azure: Create Resource..." command.
2. This issue does not reproduce when creating a resource group from context menu.

**Comment by alexweininger** [comment]
Fixed in #517 since that PR updated utils which included the fix
