### ISSUE TITLE
There is no "Open in Portal" action in the context menu

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#467]
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. Right click a resource group.
2. Check whether there is a "Open in Portal" action in the context menu.

**Expect:**
There is a "Open in Portal" action in the context menu.

**Actual:**
There is no "Open in Portal" action in the context menu.

**Comment by alexweininger** [comment]
Fixed by #505
