### ISSUE TITLE
There is no response when deleting multiple resource groups at the same time

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#469]
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. Select multiple resource groups -> Right click these resource group -> Click "Delete Resource Group...".
2. Check whether pops up the delete confirmation dialog.

**Expect:**
Pop up the delete confirmation dialog.

**Actual:**
There is no response when deleting multiple resource groups at the same time.

**More Info:**
This issue doesn't reproduce when deleting one resource group.

**Comment by alexweininger** [comment]
Fixed by #498
