### ISSUE TITLE
There are 2 "Delete Resource Group" commands in the Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#470]
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. F1 -> Search "Delete Resource Group" in the Command Palette.
2. Check whether there is only one "Delete Resource Group" command in the Command Palette.

**Expect:**
There is only one "Delete Resource Group" command in the Command Palette.

**Actual:**
There are 2 "Delete Resource Group" commands in the Command Palette.
![image](https://user-images.githubusercontent.com/45614674/209496324-0c38eb3e-79f2-493f-a724-ff243f498e6f.png)

**More Info:** (The result show as below when executing the above 2 commands)
1. There is no response when executing "Delete Resource Group...v2" command.
2. An error occurs when executing "Delete Resource Group..." command.
![image](https://user-images.githubusercontent.com/45614674/209539961-3d7db243-14aa-4caa-a103-b4e06591cc2b.png)

**Comment by alexweininger** [comment]
Fixed by #498
