### ISSUE TITLE
There is no "Focus this Group" icon for the resource group

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#471]
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. Hover the mouse on one resource group.
2. Check whether there is a "Focus this Group" icon for the resource group.

**Expect:**
There is a "Focus this Group" icon for the resource group.
![image](https://user-images.githubusercontent.com/45614674/209496996-a48aa1d8-9bc4-474e-a561-b22ff04e7f80.png)

**Actual:**
There is no "Focus this Group" icon for the resource group.

**More Info:**
1. An error occurs when executing the "Azure: Focus this Group" command from Command Palette.
![image](https://user-images.githubusercontent.com/45614674/209497220-50dc0679-7352-44f7-b3ad-e8a0eb7c03ec.png)
2. There is no "Refresh" icon for the resource group.
![image](https://user-images.githubusercontent.com/45614674/209497506-36a6ec1a-3ef8-40a5-a1fd-4aee8a9effe0.png)

**Comment by alexweininger** [comment]
This is by design, we will be replacing the Focus command with a different feature.

**Comment by nturinski** [comment]
What about the refresh icon?

**Comment by alexweininger** [comment]
Do we still need that, or does the context menu refresh work for now?

**Comment by nturinski** [comment]
I can't remember the exact reason we added it, but I thought it was a discoverability thing/replace the refresh button that used to exist on the ribbon. I'm fine with the context menu refresh though since the group nodes tend not to  have that many context actions anyway.
