### ISSUE TITLE
The error message is incomplete when entering an existed name for the new resource group

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#472]
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. Create a resource group -> Enter an existed name.
2. Check whether the errors message is complete.

**Expect:**
The error message is complete.
![image](https://user-images.githubusercontent.com/107091828/209517677-7c54b08a-0587-42ab-b500-dcc75d82bac5.png)

**Actual:**
The error message is incomplete.
![image](https://user-images.githubusercontent.com/107091828/209517620-42756ced-4b3d-43d7-8786-61c68788c8f5.png)

**Comment by MicroFish91** [comment]
Should be fixed by the PR above.
