### ISSUE TITLE
Fail to open the disk resource in portal with "404" error

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#48]
**OS:** Win 10
**Build Version:** 20201129.1

**Repro Steps:**
1. Create a VM in VS Code or portal.
2. Expand the resource group which contains the above VM in it.
3. Right click the default disk resource and select "Open in Portal".

**Expect:**
Succeed to open the disk resource in portal.

**Actual:**
Fail to open the disk resource in portal with "404" error.
![image](https://user-images.githubusercontent.com/45614674/100596429-1e546f80-3337-11eb-9fa7-6ac1949d2989.png)

**More Info:**
Add a new disk manually, it can be opened successfully in portal.

**Comment by ejizba** [comment]
How quickly after creating are you trying to open the disk? @nturinski says it's possible the disk just isn't ready. He could not repro

**Comment by v-ruizh** [comment]
@ejizba This issue can be reproduced stably when executing "Open in Portal" for a disk from resource groups view. This issue still reproduces after creating the VM one day.
But the disk opens well if open it from portal(open the resource group in portal, then open the disk from resource group).

**Note:** the disk is the default one which created during creating VM.
