### ISSUE TITLE
An error occurs when creating a Function App from Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#489]
**OS:** Win10
**Build Version:** Azure Function v1.9.1-alpha.0 + Azure Resources v0.5.7-alpha.0

**Repro Steps:**
F1 -> Azure Functions: Create Function App in Azure... / Azure Functions: Create Function App in Azure... (Advanced).

**Expect:**
It navigates to next step without any error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/209272215-0aa44332-41e9-49eb-a654-afc847d9b913.png)

**More Info:**
1. This issue also reproduces when creating a basic Function App with "Azure: Create Resource..." command.
![image](https://user-images.githubusercontent.com/45614674/209273381-f22a0b12-6a7b-4fcd-9977-7c3a724eddc7.png)
3. This issue does not reproduce when creating a Function App from context menu of Function App node.
![image](https://user-images.githubusercontent.com/45614674/209273496-d35fcef9-bf2a-4c14-aecf-be80798536f0.png)
5. There is another error when creating a basic Function App from "+" button or subscription context menu (Create Resource...).
![image](https://user-images.githubusercontent.com/45614674/209273040-ecba0dab-9a1a-43ad-bc0e-f200b5324def.png)

**Comment by alexweininger** [comment]
Fixed by #478

**Comment by alexweininger** [comment]
> 3\. There is another error when creating a basic Function App from "+" button or subscription context menu (Create Resource...).
>     ![image](https://user-images.githubusercontent.com/45614674/209273040-ecba0dab-9a1a-43ad-bc0e-f200b5324def.png)

Created new issue for this #493
