### ISSUE TITLE
An error occurs after executing "Open in Portal" action 

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#502]
**OS:** Win10
**Build Version:** 20230106.42

**Repro Steps:**

1. Right click a subscription -> Click "Open in Portal".
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/211251904-fe12c1e5-90b6-4e52-880b-c854dc64eb19.png)

**More Info:**
An error occurs after executing command "Azure: Open in Portal" from command palette.
![image](https://user-images.githubusercontent.com/107091828/211252082-f7c251fa-29ff-49da-9c62-a272afd3a5bb.png)

**Comment by alexweininger** [comment]
Fixed by #505
