### ISSUE TITLE
The function app is not refreshed after clicking "Refresh" action from context menu

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#503]
**OS:** Win10
**Build Version:** 20230106.42

**Repro Steps:**
1. Right click a function app -> Click "Refresh".
2. Check whether the function app is refreshed.

**Expect:**
The function app is refreshed.

**Actual:**
The function app is not refreshed.

**More Info:**
1. This issue **also reproduces** for the **Slot, Application Settings, Functions, Files, Logs, Deployments** and **Slot** node.
2. This issue doesn't reproduce for the subscription node.
3. This issue doesn't reproduce when clicking "Refresh" button in the Resource view.
![image](https://user-images.githubusercontent.com/57662131/211276326-8648aeda-a11e-4463-a620-c35145027bc0.png)

**Comment by alexweininger** [comment]
Fixed by #504
