### ISSUE TITLE
v2 API - Element with id "..." is already registered

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#526]
Experienced this while testing static web apps. When you expand any grouping item, it shows the following error (with a different tree item id)
<img width="468" alt="image" src="https://user-images.githubusercontent.com/12476526/214132474-ca369579-bf92-4c64-bf30-aa2e13e9724c.png">

Refreshing with things collapsed sometimes fixes it, but the error comes back on subsequent refreshes. Happens regardless of what grouping you've selected.

**Comment by alexweininger** [comment]
I'm currently investigating this and I can reproduce this consistently.

**Comment by bwateratmsft** [comment]
Is VSCode the source of that error text or is it something like this: https://github.com/microsoft/vscode-azuretools/blob/main/utils/src/tree/AzExtTreeDataProvider.ts#L116-L119

If it's the latter I'm concerned; the v1 tree framework shouldn't (mostly) be anywhere in the picture. (it will be in the compat shim)

**Comment by alexweininger** [comment]
This error is from VS Code. I've already found the source of the bug. 

I noticed a lot more resources were being resolved than were actually present, and after some digging it turns out our default Azure resource provider sometimes returns a list containing tons of duplicates. It also seems to take significantly longer when it does this. Weird...

<img width="903" alt="image" src="https://user-images.githubusercontent.com/12476526/214135447-68a33bc4-4ffe-4ce8-b738-82a5274d4c1d.png">

**Comment by bwateratmsft** [comment]
Wow, 1396! Is it coming duped straight from Azure or are we doing our listing wrong?

**Comment by alexweininger** [comment]
> Wow, 1396! Is it coming duped straight from Azure or are we doing our listing wrong?

Trying to find out now.

**Comment by bwateratmsft** [comment]
Is there a bug in our `listAllIterator` implementation?

**Comment by alexweininger** [comment]
`az resource list` also returns a list with duplicate resources, so this seems like a ARM service issue.

**Comment by alexweininger** [comment]
Fixed by #527
