### ISSUE TITLE
No error notification pops up after saving a tag with "("test"):"123"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#53]
**OS:** Win10
**Build Version:** 20201216.1

**Repro Steps:**

1. Create a new resource group. -> Right click this resource group --> Click "Edit Tags...".
2. Edit the tag with `"("test"):"123"` -> CTRL+S.
3. Check whether pop up an error notification.

**Expect:**
An error notification pops up.
![image](https://user-images.githubusercontent.com/62053665/102466675-49a2c280-408a-11eb-9073-c2f5979c57bc.png)

**Actual:**
No error notification pops up.
![re](https://user-images.githubusercontent.com/62053665/102466961-ac945980-408a-11eb-8d1b-bf74da4c2ee3.gif)

**More Info:**
The tag changes the default name and value after refreshing.
![image](https://user-images.githubusercontent.com/62053665/102471242-f3388280-408f-11eb-8169-d311e3e39004.png)

**Comment by v-chenzha** [comment]
Verified this issue on the latest main branch build 20230509.1, it still reproduces for now. Details show as below.

1. This issue doesn't reproduce on Vs Code 1.78.0.
2. This issue doesn't reproduce on Linux and Mac OS.

**Comment by Amar-QA** [comment]
This issue has been fixed in the build 20240612.1.
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/156269329/09e02de9-497f-4605-932f-a2c6310c065a)
