### ISSUE TITLE
Web Extension Runtime Issues

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureresourcegroups#543]
The following commands do not work in vscode.dev

- [x] `Azure: Create Resource`
  - Freezes on the location list step (something is probably wrong with the request)
  - https://github.com/microsoft/vscode-azuretools/pull/1381
  - https://github.com/microsoft/vscode-azureresourcegroups/pull/579
- [x] `Azure: Create Resource Group`
  - Should be the same as `Create Resource`
  - https://github.com/microsoft/vscode-azureresourcegroups/pull/579
- [x] `Azure: Edit Tags`
  - Something is wrong with the buffer
  - https://github.com/microsoft/vscode-azureresourcegroups/pull/567
  - New error `Error "parameters.properties.tags must be of type object." occurred in serializing the payload - undefined.`
  - https://github.com/microsoft/vscode-azureresourcegroups/pull/580
- [x] `Azure: Open in Portal`
  - Unable to read file (probably have to convert to VS Code fs API)
  - https://github.com/microsoft/vscode-azureresourcegroups/pull/551

**Comment by alexweininger** [comment]
> Unable to read file (probably have to convert to VS Code fs API)

I wasn't aware the open in portal ever read a file?
