### ISSUE TITLE
The .json files opened by "View Properties" are inconsistent for resource group created in Portal and VS Code

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#55]
**OS:** Win10
**Build Version:** 20210126.1

**Repro Steps:**

1. Create a resource group in VS Code -> Execute "View Properties".
2. Create a resource group in portal -> Execute "View Properties".
3. Check whether the opened .json files are consistent between the step 1 and step 2.

**Expect:**
The opened .json files are consistent between the step 1 and step 2.

**Actual:**
The opened .json files are inconsistent between the step 1 and step 2.
![image](https://user-images.githubusercontent.com/62053665/105975300-c5e8e680-60c9-11eb-921a-a861467b03d8.png)

**Comment by ejizba** [comment]
Those screenshots are functionally the same since there are no tags. The important this is just that they're the same once there _is_ any tags
