### ISSUE TITLE
The Resource Group view doesn't auto refresh after executing "Sign in to Azure..."

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#594]
**Environment:** VSCode.dev
**Regression:** Not a regression

**Repro Steps:**
1. Install the Resource Group extension.
2. Navigate to Resource Group view -> Click "Sign in to Azure..." -> Select an account.
4. Check whether the subscriptions show in the Resource Group view.

**Expect:**
The subscriptions show in the Resource Group view.

**Actual:**
The Resource Group view doesn't auto refresh. 

**More Info:** 
This issue also reproduces after executing "Sign Out/Select Subscription" command.

**Comment by nturinski** [comment]
This should be fixed by #606.
