### ISSUE TITLE
Error: g.exports.getApi is not a function

### ISSUE THREAD

**Issue by fpousserot** [microsoft/vscode-azureresourcegroups#596]
the connection to the azure account works, but when adding the azure function extension, an error appears. unable to access azure resources, create azure function, etc.

- vscode : 1.75.1
- os : windows 10.0.19045
- az function : v1.10.3
- az account : v0.9.11 (bug proxy entreprise with newest)
- az resource: v0.6.0 

with az resource v0.6.0 : Error: g.exports.getApi is not a function

with az resource v1.5.9 , the resources are displayed in the list but with another error when connecting (Error: The access token is invalid.)

**Comment by alexweininger** [comment]
This issue has been fixed in the latest release of the Azure Resources extension [(v0.6.1)](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.6.1).
