### ISSUE TITLE
Can't Create Function App in Azure - option select loops on Loading...

### ISSUE THREAD

**Issue by bartoszwalicki** [microsoft/vscode-azureresourcegroups#598]
Hi

I am working on fresh install of Azure Function Extension and recent Azure Core Tools. I can't go through first step, extension loops on Create Function app in Azure select endlessly. That completely locks VS Code UI and it needs to be rebooted.

```
Azure Functions Core Tools
Core Tools Version:       4.0.5030 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.15.2.20177

Extension
ms-azuretools.vscode-azurefunctions
Azure Functions
v1.10.3

Os
Linux version 6.1.12-arch1-1 (linux@archlinux)
```

Reproduction steps:

1. Install Azure Functions Core Tools
2. Install Azure Functions extension in VS Code
3. Login to Azure account
4. Try to execute "Create Function App in Azure"

Recording:
![](https://i.imgur.com/Oo205No.gif)

Edit:
The same behavior on macOs 13.0 (22A380).

**Comment by bartoszwalicki** [comment]
I found what was wrong, it was pretty obvious. I haven't got any subscription at all on my Azure account. After creating subscription all working as intended. It would be nice to handle this kind of case.

**Comment by alexweininger** [comment]
> I found what was wrong, it was pretty obvious. I haven't got any subscription at all on my Azure account. After creating subscription all working as intended. It would be nice to handle this kind of case.

I'm glad you found a workaround. A fix for this bug has been merged and we're hoping to release it soon. (https://github.com/microsoft/vscode-azuretools/pull/1400)

**Comment by alexweininger** [comment]
This issue has been fixed in the latest release of the Azure Resources extension [(v0.6.1)](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.6.1).
