### ISSUE TITLE
Refreshing a group item doesn't behave as expected

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#617]
Say I opened the Azure Resources view, then created a new Function App in the portal. The expected behavior of refreshing the Function Apps group in the resources view would be that the newly created Function App appears.

Currently, refreshing a group doesn't refetch the list of resources, and will not pick up newly created resources.

The easiest solution would be to make refreshing a group always do a root-refresh. A root-refresh is the only way we currently have to trigger refetching the resource list. 

Adding a way to refetch the resource list without having to refresh the entire tree might be a good thing to add in the future.

edit: Correction, a subscription refresh refreshes the resource list, so we don't have to do a root refresh.

**Comment by bwateratmsft** [comment]
Can we trap the event to refresh a group and turn it into refreshing the subscription?

**Comment by alexweininger** [comment]
> Can we trap the event to refresh a group and turn it into refreshing the subscription?

This seems to work https://github.com/microsoft/vscode-azureresourcegroups/pull/618
