### ISSUE TITLE
An error occurs after clicking "Azure: Create Resource Group..." from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#623]
**Environment:** VSCode.dev
**Build Version:** v0.6.3-alpha.0 (Preview)
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Click "Azure: Create Resource Group...".
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs. 
![image](https://user-images.githubusercontent.com/57662131/227823246-5b8f9238-63bb-45ef-9005-c1a9d0b59752.png)

**More Info:** 

1. This issue **also reproduces** after clicking "Create Resource..." button or clicking "Create Resource..." from the context menu of the subscription. 
2. This issue **also reproduces** after executing "Azure: Create Resource..." from command palette.
3. This issue **also reproduces** after executing "Group by ARM Tag…/Edit tags/Open in portal/View properties/Get Started…/ Report Issue…/Review Issues…" from command palette.
4. This issue **also reproduces** after clicking "'Group By' button-> 'Group by ARM Tag...'".
5. This issue **also reproduces** after clicking "Get Started/ Report Issue/Review Issues" action from "Help and Feedback" view.

**Comment by nturinski** [comment]
This is an issue regarding the `crypto` library being used for the "recently used" feature in quick picks. Since it's just a random uuid, I'll switch it to use `uuid` instead.
