### ISSUE TITLE
[Suggestion] It would be better to add a notification after deleting the resource group

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#633]
**OS:** Win 10
**Build Version:** 20230327.1
**Regression:** Not a regression

**Repro Steps:**
1. Make sure the setting `Azure Resource Groups: Suppress Activity Notifications` unchecked.
2. Delete a resource group.
3. Check whether there is a notification after deleting the resource group.

**Actual:**
There is no notification after deleting the resource group.

**Suggestion:**
It would be better to add a notification after deleting the resource group, like the notification after creating a resource group.
![image](https://user-images.githubusercontent.com/57662131/228187407-26a89415-0812-4add-bff5-db24ac9386ef.png)

**Comment by alexweininger** [comment]
Since we are trying to phase out use of notification for these types of operations, we likely will not be adding any _new_ notifications.
