### ISSUE TITLE
Fail to create a resource group with an error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#634]
**OS:** Win 10
**Build Version:** 20230327.1
**Regression:** previous release

**Repro Steps:**
1. F1 -> Click "Azure: Create Resource Group..." -> Enter a name -> Select a location.
2. Check whether Succeeds to create a resource group.

**Expect:** 
Succeed to create a resource group.

**Actual:**
Fail to create a resource group with an error.
![image](https://user-images.githubusercontent.com/57662131/228192608-f9d6766e-0cef-4174-86d3-ad96da024d8e.png)

**Comment by nturinski** [comment]
This should be fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/632
