### ISSUE TITLE
[Suggestion] It would be better to change the setting "Azure Resource Groups: Group By" as a drop-down list to select how azure resources are grouped

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#675]
**OS:** All
**Build Version:** 20230509.1
**Regression:** Not a regression

**Repro Steps:**
1. Open the Settings.
2. Check the `Azure Resource Groups: Group By`.

**Actual:**
This setting needs to input how azure resources are grouped. 

**Suggestion:**
It would be better to change the setting "Azure Resource Groups: Group By" as a drop-down list to select how azure resources are grouped.

**Comment by MicroFish91** [comment]
This is by design due to how we are support ARM tags
