### ISSUE TITLE
The added subscription does not show in the resource tree view

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#676]
**OS:** All
**Build Version:** 20230509.1
**Regression:** Not a Regression

**Repro Steps:**

1. Navigate to `Azure Resource Groups: Selected Subscriptions` setting.
2. Add a subscription, such as "Azure Tools Manual Testing 1".
3. Check whether the added subscription shows in the resource tree view.

**Expect:**
The added subscription shows in the resource tree view.

**Actual:**
The added subscription does not show in the resource tree view.

**More Info:**
This issue also reproduces when adding subscription by subscription ID.

**Comment by bwateratmsft** [comment]
It's worth noting, the setting will relatively soon be for both desktop and VSCode.dev/GitHub.dev.
