### ISSUE TITLE
Tenant ID is missing from values in `azureResourceGroups.selectedSubscriptions`

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azureresourcegroups#680]
These values should include the tenant ID. Blocks https://github.com/microsoft/vscode-azuretools/pull/1461.

**Comment by alexweininger** [comment]
Azure Account uses the `azure.resourceFilter` setting which is an array of strings. Each string is a tenant id and a subscription id separated by a slash.

The Resource Groups setting, `azureResourceGroups.selectedSubscriptions` is simply an array of subscription id. We should change this to match the Azure Account setting.
