### ISSUE TITLE
[Suggestion] It would be better to support multiple resources can be focused in the FOCUSED RESOURCES view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#690]
**OS:** All
**Build Version:** 20230518.3
**Regression:** Not a Regression

**Repro Steps:**

1. Create a new resource group and click the magnifying glass icon to focus it.
2. Navigate to Resources view click the magnifying glass icon to focus another resource group.
3. Check the result.

**Actual:**
The second focused resource group overwrites the first one in the FOCUSED RESOURCES view.

**Suggestion:**
It would be better to support multiple resources can be focused in the FOCUSED RESOURCES view.

**Comment by MicroFish91** [comment]
This is by design, we can only focus one
