### ISSUE TITLE
Missing one of my Resource Groups

### ISSUE THREAD

**Issue by abssd** [microsoft/vscode-azureresourcegroups#710]
Does this occur consistently? YES
Repro steps:
Click on the Azure Extension. It shows all 6 of my resource groups on another machine, but on this machine it only shows 5.

Version: 0.7.5
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

**Comment by MicroFish91** [comment]
Can you check this setting across both machines and check that they are set the same:
`azureResourceGroups.showHiddenTypes`
