### ISSUE TITLE
All subscriptions still show in RESOURCES view after unchecking all subscriptions in “Select Subscriptions" option

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#730]
**OS:** Win10
**Build Version:** 20230726.3

**Repro Steps:**
1. Sign in to Azure.
2. All subscriptions auto-show in RESOURCES view.
3. Click “Select Subscriptions…” icon -> Uncheck all subscriptions.
4. Check whether the "Select Subscriptions..." item shows in RESOURCES view.

**Expect:**
The "Select Subscriptions..." option shows in RESOURCES view.
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/45614674/d39c50b4-e656-4a8c-9bc1-44beb83e9899)

**Actual:**
All subscriptions still show in RESOURCES view.

**Comment by bwateratmsft** [comment]
This is by-design, we have changed the behavior of the select subscriptions slightly so that if zero subscriptions are returned by the filter--i.e., all were unselected--that is treated the same as no filter at all.
