### ISSUE TITLE
Latest version (0.8.0) does not support Azure USGovCloud

### ISSUE THREAD

**Issue by daronzwink** [microsoft/vscode-azureresourcegroups#768]
I spent the last couple of hours wondering why our resources weren't listed when authenticated as an Azure USGovCloud account. As soon as I manually downgraded to 0.75.0 (the most recent previous version), everything started working again. I believe there is a bug that Azure GovCloud resources cannot be listed or managed.

**Comment by tisaconundrum2** [comment]
That's so funny. I literally was just finishing up on a review on their extensions page about how 0.8.0 was completely breaking my workflow. In any case I got a response from Microsoft you can see it below.

>Hi Nicholas, sorry to hear that. Version 0.8.0 does work with Azure Gov. cloud but you need to update the `microsoft-sovereign-cloud.environment` setting in VS Code. You can set it to the "USGovernment" option.

**Comment by bwateratmsft** [comment]
@alexweininger we may want to do a 0.8.1 update with a note in the changelog and readme about how to use sovereign clouds.

**Comment by alexweininger** [comment]
Version 0.8.0 does work with Azure Gov. cloud but you need to update the `microsoft-sovereign-cloud.environment` setting in VS Code. You can set it to the "USGovernment" option. Please try that and get back to us. Sorry that wasn't properly communicated on the readme/changelog.

**Comment by daronzwink** [comment]
Given that through Azure Account, we are logged in, why can this extension just not use the same Cloud environment that the user is authenticated with? I don't think requiring a separate configuration is going to fly unless there is a valid reason I am not aware of. It should "just work" like it always has.

**Comment by bwateratmsft** [comment]
The Azure Account extension is headed for deprecation, so eventually there will still only be one configuration.

**Comment by daronzwink** [comment]
I updated to 0.8.0 again and after updating `microsoft-sovereign-cloud.environment` to "USGoverment", as soon as I authenticate to a GovCloud account, I am getting a 400 error from the callback page: `http://127.0.0.1:55906/callback?...`

<img width="876" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/11012420/ca88bc3d-265a-4293-afad-95751160c2d9">

I think there is still something not working all the way.

**Comment by alexweininger** [comment]
@daronzwink thanks for trying that out, we're now investigating it ourselves.

**Comment by alexweininger** [comment]
Submitted an issue to VS Code https://github.com/microsoft/vscode/issues/198562

**Comment by alexweininger** [comment]
Until this issue is fixed, please downgrade the Azure Resources extension to v0.7.5.

**Comment by jonathanrosshart** [comment]
Just to add to this conversation v0.8.0 is throwing AADSTS65002 when trying to log in to Azure Gov Cloud.

**Comment by alexweininger** [comment]
Sovereign cloud support is now fixed in the latest release v0.8.2.

**Comment by Lwhieldon** [comment]
Any updates to this open issue? I am having issues connecting to US Government cloud.

**Comment by alexweininger** [comment]
> Any updates to this open issue? I am having issues connecting to US Government cloud.
> 
> Looks like ms-azuretools.vscode-azureresourcegroups still can't connect to US Government Cloud.

Please try out the latest release. Looks like we commented at about the same time 😄

**Comment by Lwhieldon** [comment]
Ha! What funny timing ;-)

I still was unable to get Azure Resource extension to work with the newer version. I back dated to an older version and it's working now.

**Comment by alexweininger** [comment]
> I still was unable to get Azure Resource extension to work with the newer version. I back dated to an older version and it's working now.

Could you share any errors you are seeing and the repro steps?

**Comment by daronzwink** [comment]
I updated to version 0.8.2, and am now connected to our US GovCloud account, but there is still functionality that is not working within the Resources module.

- Not able to view Logs, the only option is to stream logs. 
<img width="343" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/11012420/cb643264-a020-4c86-809c-9f7beff7e78e">

- When clicking "Connect to Log Stream", it just hangs.
<img width="270" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/11012420/28cf9632-bc80-4759-809d-dfb41907a41b">

- Unable to view Files, it doesn't show anything.
<img width="256" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/11012420/a101325f-77dd-429b-8605-76f6b6d0fcde">

- Expanding Deployments results in 403 error.
<img width="355" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/11012420/b43263f1-ec29-49e0-9040-42fb68ad5c4d">

**Comment by Lwhieldon** [comment]
@daronzwink , thank you for providing this! That was my exact issue. :)

@alexweininger : see above from @daronzwink.

**Comment by alexweininger** [comment]
@Lwhieldon and @daronzwink please update to Azure Resources v0.8.3 to fix the issue.

**Comment by daronzwink** [comment]
@alexweininger , thanks and these functions are now working! Appreciate your support getting this new version resolved.

**Comment by alexweininger** [comment]
> thanks and these functions are now working! Appreciate your support getting this new version resolved.

Thank you for confirming. And thank you very much for your patience.

**Comment by Lwhieldon** [comment]
Thank you!!
