### ISSUE TITLE
Azure resources fetch failed

### ISSUE THREAD

**Issue by pogenechen** [microsoft/vscode-azureresourcegroups#769]
My VS Code version is 1.84.2. Azure Resources just doesn't work since last update(v.0.8.0, last released date was 2023/11/17) and keeps showing a 'fetch failed' error.
Is there anyone else encountering the same issue?

![fetch failed](https://github.com/microsoft/vscode-azureresourcegroups/assets/53831363/17ff3076-d7d7-4f5f-8715-d46b201e3fdc)

**Comment by alexweininger** [comment]
The image you added to your issue failed to upload. Can you try again? 

Could you provide repro steps and provide logs from the Azure Resources extension?

**Comment by pogenechen** [comment]
> The image you added to your issue failed to upload. Can you try again?
> 
> Could you provide repro steps and provide logs from the Azure Resources extension?

Thanks. I reuploaded the image.
I can't see there is any log for the extension by the way.
I have used azure functions and resources to deploy my programs for months. Everything was OK until last Friday when the extension was updated.

**Comment by alexweininger** [comment]
Are you using public Azure? Or a sovereign cloud?

**Comment by pogenechen** [comment]
> Are you using public Azure? Or a sovereign cloud?

I am using a sovereign cloud actually.

**Comment by pogenechen** [comment]
> If you are willing to try a beta version, you could download the vsix from here: https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/66546/artifacts?artifactName=Build&api-version=7.1&%24format=zip
> 
> Then to install, follow the steps:
> 
> 1. Extract vsix from `Build.zip`
> 2. Press F1 in VS Code
> 3. Select `Extensions: Install from VSIX`
> 4. Navigate to the new resources vsix and select it
> 5. Follow the steps in this thread: [Latest version (0.8.0) does not support Azure USGovCloud #768 (comment)](https://github.com/microsoft/vscode-azureresourcegroups/issues/768#issuecomment-1816944876)
> 6. Reload VS Code
> 
> If that solves this issue, please let us know!

It worked for me! Thanks a lot for your help!

**Comment by nturinski** [comment]
Awesome! I'm glad to hear it. :)

We will try to release this patch fix early next week so you will not have to keep using this beta version.

**Comment by dhireng** [comment]
> Are you using public Azure? Or a sovereign cloud?

for me.. same issue with public Azure. There are no logs whatsoever.

**Comment by alexweininger** [comment]
Are you still facing this issue?

**Comment by pogenechen** [comment]
> Are you still facing this issue?

The issue has never occured again. Thanks!
