### ISSUE TITLE
Cannot retrieve resources under each subscription

### ISSUE THREAD

**Issue by JLZ1783** [microsoft/vscode-azureresourcegroups#773]
Does this occur consistently? Recently occurring for 1 or more subscriptions but not all.  ( I do have appropriate permissions to view resources and can access in the portal).
Repro steps:

1. Click on <subscription dropdown> 
2.

Action: subscriptionItem.getChildren
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: resourceGroup for grouping item

Version: 0.8.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:2:787434
groupingItemFactory extension.bundle.js:2:1536309
extension.bundle.js:2:1534158extension.bundle.js:2:1534158
groupBy extension.bundle.js:2:1534144
AzureResourceGroupingManager.groupByResourceGroup extension.bundle.js:2:1535976
AzureResourceGroupingManager.groupResources extension.bundle.js:2:1534944
SubscriptionItem.<anonymous> extension.bundle.js:2:1532784
fulfilled extension.bundle.js:2:1531548
```

</details>

**Comment by nturinski** [comment]
Sorry that you're running into this issue. It seems like one of your Azure resources being listed doesn't have a resource group which is something that we (wrongly) assumed every Azure resource had.

Could you see if this workaround resolves your issue?

1. Click "Group By" on the Resources ribbon
2. Try grouping by `Resource Type`
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/5290572/df5f3e7f-ec19-4bda-80ba-d35f4f676f11)
