### ISSUE TITLE
Subscriptions not loading. Only showing "Select subcriptions..." in v0.8.0

### ISSUE THREAD

**Issue by oed-metzb** [microsoft/vscode-azureresourcegroups#775]
Hello,

Since the update to v0.8.0, I no longer see any subscriptions in the extension under "Resources".
Only the text "Select subscriptions..." appears. 
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/145457767/f09666a1-db48-44d5-bc18-699795c3e772)

When I click on "Select subscriptions...", the bar at the top of the screen opens and does not offer me any objects.
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/145457767/f6fed792-7e2b-4f3b-ae52-ef04a4f8d5b6)

I have run "Azure: Sign In (azureResourceGroups.logIn)" several times.
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/145457767/3c6753fe-de0c-4179-9df9-4386815ca1da)

If I manually downgrade to v0.7.5, the subscriptions are displayed again.
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/145457767/649a9118-bef3-4bac-ac8d-4ece80a9f2a1)

**Comment by gluc** [comment]
I have exactly the same. I tried various variations (with Device Code, with VSC Preview version, and more).

The only workaround I got to work: Downgrade to v0.7.5

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-azuretools/vsextensions/vscode-azureresourcegroups/0.7.5/vspackage

**Comment by nturinski** [comment]
Sorry for the late response. Could you try the `Azure: Sign in to Directory...` command? You can access this command by first pressing F1 and then searching for the command.

**Comment by oed-metzb** [comment]
No problem,
when i try to run (with v0.8.0 installed) `Azure: Sing in to Directory...`i only get a new prompt "Select Directory to Sign In To"
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/145457767/1f7002e8-e0c4-4f70-96a2-1113e261f265)
But i can't select anything or when i try to enter `<tenant>.onmicrosoft.com` i can`t proceed.
I also tested the latest version v0.8.4, but the same result.

v0.7.5 is still my workaround to access the resources.

**Comment by alexweininger** [comment]
The "Sign in to Drectory..." command will list any directories (or tenants) that aren't already authenticated. In the screenshot it isn't showing you have any unauthenticated directories. Do you know if you have multiple directories (also called tenants) available to your account?

Are you working in the public Azure cloud or a sovereign cloud? We have a new setting you need to use if you are using a sovereign cloud.

My last suggestion is to try to reset or reinstall as much as you can. Log out of your browser and also out of VS Code. And maybe even reinstall the extension. I'm really sorry about this, our new authentication is supposed to fix subscriptions not showing up 😢.

**Comment by aburgessPARS** [comment]
Same issue. Using azure government US cloud. Where is the new setting?

**Comment by alexweininger** [comment]
@aburgessPARS To connect to a sovereign cloud, set the `microsoft-sovereign-cloud.environment` setting to `USGovernment`.

<img width="672" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/12476526/d2ea6c2e-acf9-45ab-8b79-8257e4cb3b39">

**Comment by alexweininger** [comment]
@oed-metzb, are you also using a sovereign cloud?
