### ISSUE TITLE
Resources not showing up after Azure Gov Sign In

### ISSUE THREAD

**Issue by daniel-balandran** [microsoft/vscode-azureresourcegroups#785]
I am not sure what I need to place in the support ticket. As of 11/29/23 I can no longer view my resources in my VS Code. I have successfully logged in via Azure: Sign in to Azure Cloud (Azure US Government) and Sign in with Device Code. Each time I get that I have signed in, but when I go back to my VS Code I am not seeing my resources.

I am able to see my sign in account at bottom of editor in Azure Account Status. I am also able to see my subscriptions in Command Pallet when I click on the account email.

I have cleared out the Code and ~./vscode directories and reinstalled Azure Tools (I am on a MacBook Pro Monterey 12.7).

Any help would be great. Thank you!

![Screen Shot 2023-12-01 at 9 56 53 PM](https://github.com/microsoft/azcode/assets/37518044/40704311-d2bd-4bb5-aaaa-0f2687790fb3)

**Comment by alexweininger** [comment]
Hi this is a known issue with the latest release of the Azure Resources extension (v0.8.0), we have a fix and plan to release it ASAP. In the meantime, please rollback Azure Resources to v0.7.5.

**Comment by daniel-balandran** [comment]
Thank you very much for responding. Rolling back worked!

**Comment by alexweininger** [comment]
Sovereign cloud support is now fixed in the latest release v0.8.2.
