### ISSUE TITLE
Missing icons on Workspace menu toolbar

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-azureresourcegroups#788]
In the workspace view there are two missing icons for Static Web Apps and Databases

https://github.com/microsoft/vscode-azureresourcegroups/assets/4821/14165804-b8e3-47cf-ad4c-c90a9ca793bc

**Comment by nturinski** [comment]
Thanks for reporting this. We've fixed this, but haven't released them yet.

As a workaround, you can use dark theme as this only occurs on light theme (weird).
