### ISSUE TITLE
Unable to select proper subscription

### ISSUE THREAD

**Issue by MohitSurase** [microsoft/vscode-azureresourcegroups#789]
Even after successful sign in into the Azure account, I am unable to select the proper subscription associated with the respective account.

**Comment by alexweininger** [comment]
Make sure you are using the "Azure: Select Subscriptions..." command, and not the "Azure: Select Subscriptions" command. The second one is contributed by the Azure Account extension which is no longer used by the Azure Resources extension.
<img width="613" alt="image" src="https://github.com/microsoft/azcode/assets/12476526/fefd3813-8750-4c5d-90b2-24e54587ea83">

We know this is confusing and we're working to remove these old commands.
