### ISSUE TITLE
Timed out waiting for authentication provider to register

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#790]
> I'm having a similar issue with this. I can confirm this is happening with the 0.8.0 version of the extension and it's not happening on the 0.7.5. In my case I'm not using any sovereign Azure. And in my case the thrown error when this happens is as follows:
> 
> Timed out waiting for authentication provider to register.
> 
> A little more of information:
> 
> It is fixable if you downgrade to the v0.7.5 and refresh the resources submenu. If you upgrade to the 0.8.0 you still can see the resources until you close your VSCode instance.

_Originally posted by @eliasrodeloso in https://github.com/microsoft/vscode-azureresourcegroups/issues/780#issuecomment-1852871343_

Created a new issue for this. We'll probably need to ask VS Code for help on this one. I've seen it a few times in Static Web Apps with the GitHub auth provider too so I think it could be a bug in VS Code.

**Comment by nturinski** [comment]
Do you know if that error consistently reproduces for some people? I've had this happen to me too, but I can't always repro it.

**Comment by alexweininger** [comment]
It's inconsistent and you can get rid of it by restarting VS Code and/or re-installing the extension.

**Comment by eliasrodeloso** [comment]
In my case I can't get rid of it I restart my VSCode, only by reinstalling the 0.7.5 version of the extension.

**Comment by alexweininger** [comment]
The Azure Resources extension depends on the Microsoft Authentication extension which is built in to VS Code. It's possible that this extension is disabled, which might be causing this error. Please check that you have the Microsoft Authentication extension enabled.

<img width="432" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/12476526/ffc8e9d9-adac-4ac5-9e77-87c906e9dd7e">

**Comment by nturinski** [comment]
@eliasrodeloso and @mat-ej 

Were you able to try Alex's suggestion? 

> The Azure Resources extension depends on the Microsoft Authentication extension which is built in to VS Code. It's possible that this extension is disabled, which might be causing this error. Please check that you have the Microsoft Authentication extension enabled.
> 
> <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/12476526/295318407-ffc8e9d9-adac-4ac5-9e77-87c906e9dd7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzIwOTMsIm5iZiI6MTcwNzMzMTc5MywicGF0aCI6Ii8xMjQ3NjUyNi8yOTUzMTg0MDctZmZjOGU5ZDktYWRhYy00YWM1LTllNzctODdjOTA2ZTlkZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE4NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZjRmM2UxMWEwYTRlMWQwNmJhODQwNzczNmI1MDc2ZWJmYzVlOTkyY2M4MGEyNzkzNmYyNzJkYzU1N2E5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ug2Km1ow93h3Y2x237EdNeZOPF9BI73_pam-gXmHFw">

Please let us know if this resolved the issue for you.
