### ISSUE TITLE
Unable connect to Azure in VSCode

### ISSUE THREAD

**Issue by PeterbASKSd** [microsoft/vscode-azureresourcegroups#797]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureResourceGroups.logIn
Error type: Error
Error Message: Network failure

Version: 0.8.3
OS: darwin
OS Release: 23.0.0
Product: Visual Studio Code
Product Version: 1.85.1
Language: en

<details>
<summary>Call Stack</summary>

```
f.J extension.js:1:215864
f.I extension.js:1:214775
f.u extension.js:1:207200
f.r extension.js:1:206235
Object.createSession extension.js:1:508034
```

</details>

Tried:
1. Unchecked http.systemcertificate
2. Don't have any proxy
3. Remove expired keychain
4. Remove all extension

**Comment by nturinski** [comment]
Does this happen consistently? Could you provide logs from the Microsoft Authentication extension? You should be able to see it in your output channel and selecting `Microsoft Authentication` in the drop-down.

![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/5290572/07e0749b-7893-476c-9a59-a6ca5869b699)
