### ISSUE TITLE
Azure Resources extension on wsl ubuntu doesn't work with ChinaCloud

### ISSUE THREAD

**Issue by chris-han** [microsoft/vscode-azureresourcegroups#798]
It works after switched back to v0.6.2. 
It seems any versions beyond v0.6.2 has trouble to show resources in ChinaCloud. 
The "Azure: Sign in to Azure Cloud " prompt works fine with logging into ChinaCloud.

**Comment by alexweininger** [comment]
Can you verify that logging into ChinaCloud doesn't work when using the latest extension version? Make sure to set the  set the `microsoft-sovereign-cloud.environment` setting to "ChinaCloud".

<img width="810" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/12476526/2b75f5c1-11e3-4eb9-a6e2-fbffc31653f5">
