### ISSUE TITLE
Azure Resources: Select Subscriptions

### ISSUE THREAD

**Issue by mtkono** [microsoft/vscode-azureresourcegroups#804]
When working with v0.8.3 resources don't show and instead I get "Select subscriptions". 
![obraz](https://github.com/microsoft/azcode/assets/137612738/78b106d1-11d1-4262-9ca9-fdfce0020072)

However, no subscription can be selected.
![obraz](https://github.com/microsoft/azcode/assets/137612738/69b8019b-aac7-438b-8bec-5b847f413fea)

When I downgraded to 0.7.1 all works fine.
![obraz](https://github.com/microsoft/azcode/assets/137612738/0450072c-6918-4b75-aa56-b8bccb06bc75)

I am working on Linux Mint.

**Comment by alexweininger** [comment]
Could you try using the "Azure: Sign in to Directory..." command?
