### ISSUE TITLE
Azure Resource VSCode Extension not showing US Gov Subscriptions when logged in

### ISSUE THREAD

**Issue by amorrow-flexion** [microsoft/vscode-azureresourcegroups#817]
Does this occur consistently? Yes
preconditions: 
- MAC OS
- US Gov Azure Subscription

Repro steps:
1. Install VS Code Extension for Azure Resources
2. Azure: Login through cmd > shift > p 
3. successfully authenticate to tenant
4. within the Azure extension blade, click "Select Subscription..."

- Expected: My subscription should be available for use in the prompt to select subscriptions above
- Actual: Extension does not display any subscriptions available. See Below:

<img width="1232" alt="Screenshot 2024-02-08 at 9 04 04 AM" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/133667008/fa56f2bb-d7bb-4e6f-928f-0e96bf8182ca">

I followed several troubleshooting steps, none of which proved successful:
1. Removed all Azure related extensions including this one, and reinstalled the Azure Resources extension only, signed out using Azure: Sign Out and attempted to sign in again
2. Signed out of the azure account within the AZ Cli, the extension with cmd> shift > p Azure: Sign Out (also clearing the tenant ID), and within my browser. Then authenticated to try and populate subscriptions
3. Attempted to use "Azure: Sign in to Azure Cloud..." to authenticate.
4. Attempted to add subscription directly to the Azure extension settings within VS Code

Version: 0.8.4
OS: darwin
OS Release: 23.2.0
Product: Visual Studio Code
Product Version: 1.86.0
Language: en

**Comment by alexweininger** [comment]
To connect to a sovereign cloud, set the `microsoft-sovereign-cloud.environment` setting. This is new as of v0.8.0 and is a result of our migration to the built-in Microsoft authentication extension which replaces the Azure Account extension. [Learn more in the release notes.](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)

**Comment by nturinski** [comment]
Closing due to a lack of activity/response. Hopefully the wise @alexweininger was able to help resolve this issue.
