### ISSUE TITLE
MY RESOURCE GROUP AND SUBSCRIPTION IS NOT SHOWING EVEN THOUGH I HAVE SIGNED IN AND SO I CANNOT DEPLOY MY APP TO THE WEB

### ISSUE THREAD

**Issue by GoodnessOno** [microsoft/vscode-azureresourcegroups#824]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.8.4
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.86.2
Language: en

**Comment by alexweininger** [comment]
Hi, can you give more information about the issue you are facing? Are there any errors? Including screenshots will help a lot.

**Comment by GoodnessOno** [comment]
> Hi, can you give more information about the issue you are facing? Are there any errors? Including screenshots will help a lot.

Thank you so much, it has been resolved
