### ISSUE TITLE
Issue: New resources do not show up in the resouces panel

### ISSUE THREAD

**Issue by estruyf** [microsoft/vscode-azureresourcegroups#827]
I wanted to create a new Azure Function from the resources panel to publish a quick sample. The function creation process works fine, but once it's created, it doesn't show up in the panel.

Here, you can see the output of the creation process:

<img width="1095" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/2900833/39127abf-a178-46fe-85ed-dbabb099f1c6">

When I refresh the resources, I see the new resource group, but when I expand it, it doesn't show any resources:

<img width="337" alt="Screenshot 2024-03-05 at 13 54 00" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/2900833/01963a67-6cf6-4e56-b00b-6e4759973314">

Other Azure resources are shown correctly:

<img width="335" alt="Screenshot 2024-03-05 at 13 56 08" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/2900833/45f39436-8a80-49be-8c63-d7bad6425ff4">

It feels that only new resources aren't showing up. Tried it with a different account + tenant, and it has the same issue.

**Comment by motm32** [comment]
Are you still facing this issue?
