### ISSUE TITLE
Cannot load resources for subscription. Loading indicator just spins...

### ISSUE THREAD

**Issue by ameltzer-MSFT** [microsoft/vscode-azureresourcegroups#832]
Does this occur consistently? 
Yes
Repro steps:

This worked earlier today, but just stopped working.

I am able to sign in and view subscriptions, but when I click on a subscription to view its resources, it just sits there with a loading indicator.

I've tried uninstalling and reinstalling the extension, and signing out/back in to Azure but it doesn't resolve the issue.

![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/146774953/72bea8b4-b741-4846-97c9-5cfeed82f7a9)

Version: 0.8.4
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.87.2
Language: en

**Comment by alexweininger** [comment]
Hi @ameltzer-MSFT, are you still facing this issue?

**Comment by ameltzer-MSFT** [comment]
It has been fine today. Closing.
