### ISSUE TITLE
Switching Tenant/subscriptions in VScode

### ISSUE THREAD

**Issue by gherik** [microsoft/vscode-azureresourcegroups#835]
I have multiple Azure tenants and subscriptions, I'm trying to switch tenant/subscription. But VScode (Azure extension) still shows the other tenant/subscriptions. I logged out and logged back in, restarted VScode. But the "old" tenant/subscription is "sticky".
What am I doing wrong, this hassle with switching tenants/subscription takes so much time that it is starting to irritate me.

**Comment by alexweininger** [comment]
Hi, you can switch tenants using the "Azure: Sign in to Directory..." command. Access it in the command palette.
