### ISSUE TITLE
An error occurs when installing the extension from the expanded resource

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#838]
**OS:** All
**Build Version:** 20240413.1
**Regression:** Previous release (0.8.4)

**Repro Steps:**
1. Resources group by Resource Type.
2. Expand App Service node -> Expand an app service -> Click "Install extension to enable..." -> Click "Install" in the opened marketplace page.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/57662131/a2e2895d-6bf2-4f56-b3e8-c83207491adf)

**More Info:** 
This issue also reproduces when installing other extensions.

**Comment by alexweininger** [comment]
Fixed by #839
