### ISSUE TITLE
VS Code Azure Resources v.0.8.4 is not working as expected

### ISSUE THREAD

**Issue by lbernstein1969** [microsoft/vscode-azureresourcegroups#841]
VS Code Azure Resources v.0.8.4 is not working as expected.
I downgraded to version v0.7.1 and it works.
When I do Ctrl+Shift+P in VSCode and select "Azure Functions: Deploy to Function App..." I should be able to select subscription first - I have two: Development and Producion. After selecting subscription I should be able to select resource group.

v0.7.1 does exactly this.
However upgrading to Azure Resources v.0.8.4, skips the subscription step and shows resource groups but it is not even a full list of the resource groups I have.

**Comment by alexweininger** [comment]
If you only have one subscription selected in the resources view, like this:
<img width="386" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/12476526/b3e1ea1d-bb4d-4e52-9686-194e61054910">

the subscription step will be skipped automatically, picking the single filtered subscription.

To change your selected subscriptions use this icon here on the subscription
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/12476526/bb4e4761-b1bc-456a-815c-41da07593e35)

Or use "Azure: Select Subscriptions..." from the command palette. Make sure to not use the older "Azure: Select Subscriptions" command that is from the Azure Account extension that is no longer used by our extensions and is in the process of being deprecated.
