### ISSUE TITLE
Unable to see subscription under resources (Azure US Gov)

### ISSUE THREAD

**Issue by egyptiangodraw** [microsoft/vscode-azureresourcegroups#847]
I went through several articles that were recently posted regarding how to sign in to US Gov Cloud by changing settings to custom but I have had no luck. Maybe I am not doing it currently. Any help would be greatly appreciated. TIA

I am using the latest version of the extension. Tried rolling it back to 0.8.0 and a couple others but no luck.

**Comment by alexweininger** [comment]
To connect to a sovereign cloud, set the `microsoft-sovereign-cloud.environment` setting to "USGovernment". 

<img width="1239" alt="image" src="https://github.com/microsoft/vscode-azureresourcegroups/assets/12476526/f5dcf8d3-1126-4430-943a-47058b20a0c0">


This is new as of v0.8.0 and is a result of our migration to the built-in Microsoft authentication extension which replaces the Azure Account extension. [Learn more in the release notes.](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)

**Comment by egyptiangodraw** [comment]
Hi Alex, thanks for responding. I actually came across your previous posts and did try changing that in quite a few different ways but can’t seem to get it working. See screenshot below. 

![4C610D69-249B-487F-8B4D-435971CAC070](https://github.com/microsoft/vscode-azureresourcegroups/assets/168617811/e052217b-23c8-401e-8779-8c2285ae61bd)

**Comment by egyptiangodraw** [comment]
Got it!! There was one more step after changing the setting to US Gov, you have to sign in via the “Azure: Sign In azureResourceGroups.logIn” instead of “Azure: Sign In to Azure Cloud”. See below. 

![667DB169-7CB2-43FB-87B7-9DB4736F2EC3](https://github.com/microsoft/vscode-azureresourcegroups/assets/168617811/004031f8-963c-4d42-bfe8-19e0b165fe08)

**Comment by alexweininger** [comment]
> Got it!! There was one more step after changing the setting to US Gov, you have to sign in via the “Azure: Sign In azureResourceGroups.logIn” instead of “Azure: Sign In to Azure Cloud”.

Yes, very sorry about that. We are in the process of getting rid of the older Azure Account extension and its commands. Currently not the greatest experience...
