### ISSUE TITLE
Unable to Login with Proxy Settings

### ISSUE THREAD

**Issue by Vangas-ConEd** [microsoft/vscode-azureresourcegroups#86]
Product:               Visual Studio Code
Issue:                    Visual Studio Code is unable to connect to Azure services through extensions, and showing below error 
Error: request to https://management.azure.com/subscriptions?api-version=2016-06-01 failed, reason: unable to get local issuer certificate

Trying to connect through company proxy settings.
Turning off proxies and firewalls resolves the issue temporarily.

Need a permanent solution to use Azure Services through VSCode with company firewall settings.

**Comment by ejizba** [comment]
Here are the docs on using a proxy with VS Code: https://code.visualstudio.com/docs/setup/network
