### ISSUE TITLE
The "Azure Cloud Shell (Bash)" is not support in Azure China account

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureresourcegroups#866]
**OS:** All
**Build Version:** 20240525.1
**Regression:** Not a regression

**Repro Steps:**

1. Make sure setting "Microsoft-sovereign-cloud: Environment" to ChinaCloud.
2. Sign out.
3. Open VS Code's Terminal view and click the dropdown to create a new terminal -> Select "Azure Cloud Shell (Bash)".
4. Click "Open" button after pop up a notification.
5. Check whether the opened page is the Azure China account portal.

**Expect:**
The opened page is the Azure China account portal.

**Actual:**
The opened page is the Azure account portal.

**More Info:**
The Azure China account portal doesn't have Cloud Shell command.
![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/107091828/a8a78870-3a32-42d1-83ac-58233f225132)

**Comment by nturinski** [comment]
Do you know if this used to work when we did it through Azure Accounts?

**Comment by v-chenzha** [comment]
It works when through Azure Accounts. But it doesn't work in Azure Account Extension. There are two related bugs:
https://github.com/microsoft/vscode-azure-account/issues/484
https://github.com/microsoft/vscode-azure-account/issues/257

**Comment by alexweininger** [comment]
Azure Cloud Shell is not supported in Azure China.
