### ISSUE TITLE
Extension shows placeholder names (e.g. %azureResourcesGroups.refresh%) for settings, commands, etc. Everything broken

### ISSUE THREAD

**Issue by lavendelchen** [microsoft/vscode-azureresourcegroups#867]
OS: WSL Windows 10

I might have installed and uninstalled different azure vscode extensions too many times, now everything is just broken and I have no idea how to fix it except reinstall vscode completely?

Currently there are the Azure Account and Azure Resource Groups extension installed. I have tried with only installing one of them, all produces the same result. 
I will share some example screenshots:

![tmp_763cc1cb-a0dd-4956-aebf-23b8dd319186.png](https://github.com/microsoft/vscode-azureresourcegroups/assets/80402215/966876d7-b1cd-4f6f-a34f-d70e7e5d2afc)

![tmp_3f8d5a38-e4c9-4d40-bb5e-b093e5ba3ae4.png](https://github.com/microsoft/vscode-azureresourcegroups/assets/80402215/1042f161-8451-4982-a04a-358d43d9187a)

If I try to do any action, it causes errors, like creating a new resource:

![tmp_be950c49-bd16-4381-b758-c9328a002c98.png](https://github.com/microsoft/vscode-azureresourcegroups/assets/80402215/42031036-191c-4310-835d-c38de1c30352)

![tmp_a0f3daf4-df7e-473c-a9ba-588a0f0c3583.png](https://github.com/microsoft/vscode-azureresourcegroups/assets/80402215/bc21ba04-2324-48dd-b8c6-c066b56ba036)

or executing any command:

![tmp_748e40ae-cc10-469b-b032-caea7314d562.png](https://github.com/microsoft/vscode-azureresourcegroups/assets/80402215/da5a837b-5a24-44cf-8fd3-e9109ff65036)

![tmp_92f08b7c-8a8e-4de9-aa5a-7178b387ece8.png](https://github.com/microsoft/vscode-azureresourcegroups/assets/80402215/9d50223b-16b9-427e-b460-e096b3c39d3f)

**Comment by lavendelchen** [comment]
**Update**
Solved by manually deleting extension caches in WSL and installing the extension again after. 

Steps:
1.  Navigate to `/home/<user>/.vscode-server/extensions/` in WSL terminal
2. Look for any azure-related folders in there, e.g. `ms-azuretools.vscode-azureresourcegroups-<version>`
3. Delete them with `rm -rf`
4. Close VSCode
5. Reopen and reinstall extension(s)

**Comment by nturinski** [comment]
I'm glad that you were able to resolve it! Closing for now since it doesn't seem like something that we can control on our end.
