### ISSUE TITLE
Extension hijacks "Toggle Block Comment" keyboard shortcut

### ISSUE THREAD

**Issue by Zache** [microsoft/vscode-azureresourcegroups#870]
This extension registers the keyboard shortcut: **Shift**+**Alt**+**A** to open itself in sidebar of VSCode, but that keyboard shortcut is already used by the default configuration of VSCode as "Toggle Block Comment" that comments out your current selection.

To me this feels like bad manners, and I think you should change it. 

Looking at the keyboard shortcuts it seems like focusing the different sidebars uses **Ctrl**+**Shift** and not **Shift**+**Alt**. Perhaps it's better to follow that pattern? **Ctrl**+**Shift**+**A** is already taken (but only works when a notification is focused or a toast visible), but I can see that GitLens has opted for a chord and selected **Ctrl**+**Shift**+**G** **G** instead of hijacking the default shortcut for "View: Show Source Control"

**Comment by Zache** [comment]
Windows

**Comment by alexweininger** [comment]
This has been fixed in #876
