### ISSUE TITLE
Couldn't able to login into azure account

### ISSUE THREAD

**Issue by Yashasvi0884** [microsoft/vscode-azureresourcegroups#878]
Couldn't able to login into azure account in vs code

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azureresourcegroups/issues/877
- [ ] https://github.com/microsoft/vscode-azureresourcegroups/issues/877
```

**Comment by nturinski** [comment]
Authentication is now handled by the Azure Resources extension.  Please use this command to sign in

![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/5290572/99009e31-97e9-46b4-8571-7504a2d28a96)

If this does not solve your issue, please provide details about your VS Code and Azure Resources versions and detailed repro steps.
