### ISSUE TITLE
[Codespaces] The link in the dialog that asked to open the another external website is incorrect after opening a resource group in portal

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureresourcegroups#89]
**Environment:** Remote Codespaces
**Build Version:** 20210608.1

**Repro Steps:**

1. Right click one resource group -> Click "Open in Portal" -> Click "Open" when asking to open the external website.
2. Right click another resource group -> Click "Open in Portal".
3. Check whether the link in the dialog is correct.

**Expect:**
The link in the dialog is correct.

**Actual:**
The link in the dialog is incorrect.

**More Info:**
This issue also reproduces for other Azure extensions, so I think it is most likely a **GitHub Codespaces** issue.

**Comment by ejizba** [comment]
How are the links incorrect? Is it using an old link or some other random link? This is likely a VS Code core issue that is out of our control

**Comment by v-mengwe** [comment]
Verified on the latest build 20210629.1, this issue doesn't reproduce for now, so close it.
