### ISSUE TITLE
Unable to authenticate to USGov link after it changed from portal.azure.us to portal.azure.us/vaazuregov.onmicrosoft.com

### ISSUE THREAD

**Issue by egyptiangodraw** [microsoft/vscode-azureresourcegroups#898]
I used to be able to Sign In to AzureGov using VS Code  via the USGov method. However, the URL has changed as mentioned in the title and the authenticator that pops up still points to portal.azure.us instead of portal.azure.us/vaazuregov.onmicrosoft.com. Any help on how I can authenticate would be appreciated. Thanks

**Comment by MicroFish91** [comment]
Hi, we have a user setting under `Microsoft-sovereign-cloud` where you can set `custom`.

![image](https://github.com/user-attachments/assets/43f6c86f-22b3-4bd5-a57f-f2006ac134a9)

You can then specify a custom resource management endpoint url by clicking `edit in settings.json` and adding it here:

```json
"microsoft-sovereign-cloud.customEnvironment": { },
```

To get to your user settings you can press F1 > `Preferences: Open User Settings` and search the above text.  Please let me know if this helps!

**Comment by egyptiangodraw** [comment]
Thanks so much for your assistance. I’ve tried the following but haven’t had much luck. The two parameters that I am sure about are the portalURL since that is what I am trying to authenticate to and the resource manager endpoint URL. However not sure about the other management endpoint url, active directory url, or the directory ID. 


Based on my portal URL if you can point out how to proceed I’ll really appreciate it. TIA

{
  
    "azure.cloud": "AzureCustomCloud",
    "microsoft-sovereign-cloud.environment": "custom",
    "microsoft-sovereign-cloud.customEnvironment": {
    "name": "TestAzureGov",
    "activeDirectoryEndpointUrl": https://login.microsoftonline.us/,
    "activeDirectoryResourceId": "Not sure where to find this",
    "managementEndpointUrl": "Not sure",
    "portalUrl": https://portal.azure.us/testazuregov.onmicrosoft.com,
    "resourceManagerEndpointUrl": https://management.usgovcloudapi.net/
    }
}

**Comment by alexweininger** [comment]
Does it work if you set the Environment setting to "USGovernment" instead of custom?
