### ISSUE TITLE
Azure resources not updating after signing into another account

### ISSUE THREAD

**Issue by zeromonad** [microsoft/vscode-azureresourcegroups#902]
The resources in the resource list are always staying the same despite signing into another Azure account. I am using the azureResourcesGroup.login signin method. I have tried signing out, reloading visual studio code. 

When I try to select the subscriptions, I only see the subscriptions from the very first account I added. Is there a way to add more? This seems like a bug.

**Comment by alexweininger** [comment]
We are working on support for multiple accounts in #869, until then you need to make sure the only Microsoft account signed in, is the one you want to display resources for. To check how many you have signed in, use the Accounts menu and see how many are signed in that show "(Microsoft)". In the screenshot I only have one.
<img width="406" alt="Screenshot 2024-08-20 at 10 02 21 AM" src="https://github.com/user-attachments/assets/9944f020-1bad-44cf-b9c7-97d831933ef0">
