### ISSUE TITLE
V0.9.2 causes error when deploying to function app

### ISSUE THREAD

**Issue by mwdavids** [microsoft/vscode-azureresourcegroups#904]
Downgrading to v0.9.1 solves the issue, but with version 0.9.2 my colleagues and I get the following error message deploying to a function app:

Operation 'Microsoft.Web/sites/read' failed as server encountered too many requests. Please try after '60' seconds. Tracking Id is ________

**Comment by alexweininger** [comment]
This has been fixed in v1.15.3 of Azure Functions.
