### ISSUE TITLE
v0.9.2 - Error loading resources on USGovernment with subscription could not be found

### ISSUE THREAD

**Issue by daronzwink** [microsoft/vscode-azureresourcegroups#905]
After my extension upgraded to v0.9.2 my resources all display the following issue:

`The subscription 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found.`

I have signed out and verified I have used the newer "Azure: Sign In" (azureResourceGroups.login) to re-authenticate and still no luck. I have also tried from two different machines and no luck.

After downgrading to v0.9.1, everything works great.

**Comment by daronzwink** [comment]
@alexweininger, thank you!

**Comment by alexweininger** [comment]
The fix will be included in the next version. We're aiming to get it out next week.

**Comment by alexweininger** [comment]
Hi @daronzwink, the fix has been released in the latest version, v0.9.5 https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.9.5
