### ISSUE TITLE
First launch of Cloud Shell in a directory requires setup - USGovernment

### ISSUE THREAD

**Issue by devopsjesus** [microsoft/vscode-azureresourcegroups#911]
I have successfully setup the Azure Resources extension in VS Code to authenticate to my directory/tenant. However, when launching a CloudShell for the first time, I am encountering an issue with successfully completing setup. The toast popup that opens the page to authenticate for 'first launch' is shell.azure.com. I can input my gov account (ending in .us) and the login prompt will successfully authenticate, but I am simply sent to the portal (portal.azure.us). Meanwhile, the CloudShell session in VS Code is closed after clicked 'Open' on the toast popup. Hoping to use this capability to reduce security footprint on 'developer PAWs'.

**Comment by alexweininger** [comment]
If you go to the USGovernment portal directly and access cloud shell there, are you able to go through the setup process? Once you set it up there it _should_ work properly within the extension.

**Comment by devopsjesus** [comment]
I did go into the portal and setup the cloudshell (with ephemeral storage) - perhaps this is an issue with setting up the storage account?

**Comment by alexweininger** [comment]
Ok, so even after setup in the portal the extension indicates that setup is still required via that notification?

**Comment by devopsjesus** [comment]
Yes, that’s correct:
![image](https://github.com/user-attachments/assets/01ba21ae-9b97-4b59-938f-d61fca1cd58d)

**Comment by devopsjesus** [comment]
bump

**Comment by alexweininger** [comment]
Was this working before and recently break? Does reverting back to v0.9.1 of the Azure Resources extension fix the issue?

**Comment by devopsjesus** [comment]
This was the first time attempting to connect with the extension. I did just revert to v0.9.1 and see the same error.

**Comment by devopsjesus** [comment]
bump - this is for an environment with > 250K users :)

**Comment by alexweininger** [comment]
Thanks for the bump. I've identified two separate issues contributing to the bug you're experiencing. I'm currently working on getting them fixed to unblock you.

**Comment by alexweininger** [comment]
Hi @devopsjesus, I have a dev build with a fix. If you can verify that it works for you that will help me out a lot.

Steps to install extension development build:
1. If needed, update VS Code to `1.66.0` or greater.
1. Download the zip archive which contains the extension .VSIX: [vscode-azureresourcegroups-0.9.6-alpha.0.vsix.zip](https://github.com/user-attachments/files/17066011/vscode-azureresourcegroups-0.9.6-alpha.0.vsix.zip)
1. Extract the VSIX from the .zip archive
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.

**Comment by alexweininger** [comment]
The fix for this issue has been released in [v0.9.6](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.9.6).
