### ISSUE TITLE
Extension can't log in to Azure subscription

### ISSUE THREAD

**Issue by yk2492** [microsoft/vscode-azureresourcegroups#912]
I'm using Azure Extensions for deploying Function Apps and LogicApps workflows.
Open the Azure tab and click Sign in to Azure... , after completing the login operation in the browser, a Network failure error is displayed.

I noticed this issue on 8/28.
I used to be able to use it, but suddenly I can't log in.
I'm using a proxy.

OS:Windows 11.
Extension:
 Azure Resources v0.9.4
 Azure Functions v1.15.3
 Azure Logic Apps (Standard) v4.57.7
 Azure Account v0.12.0

I am sorry. Image upload fails.

**Comment by eolver** [comment]
@yk2492   fixed this issue although i am not using proxy

I did the following

Preferences > Settings > Extensions > Microsoft Account > Microsoft 
Enabled 'Use Msal'

Restarted VS Code and it resolved.

**Comment by yk2492** [comment]
@eolver 
Thanks for the support!
I enabled the 'Use Msal' setting and the problem was solved.

The 'Use Msal' setting appeared when I updated the VSCode version to 1.93.0.

**Comment by yk2492** [comment]
Close the issue because the issue is resolved.

**Comment by alexweininger** [comment]
Thanks for the help @eolver! TIL about the new Use Msal setting.
