### ISSUE TITLE
Can not view the storage account in Azure China, error: Could not resolve resource xxx

### ISSUE THREAD

**Issue by JohnTangZX** [microsoft/vscode-azureresourcegroups#917]
VS Code Version: 1.93.0
OS Version: Windows 11

Steps to Reproduce:

1. Sign in to Azure China after modifying the settings as below.
![image](https://github.com/user-attachments/assets/8273cd54-685a-4007-8c62-7ca905687e1b)

2. Install the latest extensions, for example "Azure Storage v0.16.1" and "Azure Resources v0.9.4", then I can see the below error for the storage account. The issue happens for all resources, not specific to storage accounts.
![image](https://github.com/user-attachments/assets/81c2495a-b74a-4a4f-a51e-834671a58d5c)

3. The signed in account is the owner of the resources.

4. I am able to create the storage account, but can not view it. The error is as below.

Output of Storage account:
Error: The subscription 'xxxx-b158-4cfc-b303-xxxxx' could not be found.
Creating resource group "testvssa" in location "China North 3"...
Successfully created resource group "testvssa".
Creating storage account "testvssa" in location "China North 3" with sku "Standard_LRS"...
Successfully created storage account "testvssa".
Error: The subscription 'xxxx-b158-4cfc-b303-xxxx' could not be found.

Output of Azure resource Groups:

2024-09-09 12:59:58.260 [info] Internal error: 'branchDataProvider.getResourceItem' threw an exception
Could not resolve resource "/subscriptions/xxx-b158-4cfc-b303-xxx/resourceGroups/testvssa/providers/Microsoft.Storage/storageAccounts/testvssa"
at CompatibleApplicationResourceBranchDataProvider. extension.bundle.js:2:1541296
fulfilled extension.bundle.js:2:1540321

5. I am able to see the storage accounts and othre resources after installing the old version extension "Azure Resources v0.8.1".

**Comment by JohnTangZX** [comment]
Okay, thank you for your help!

**Comment by alexweininger** [comment]
Hi @JohnTangZX, the fix has been released in the latest version, v0.9.5 https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.9.5
