### ISSUE TITLE
Getting Network Failure when trying to sign in to Azure Account. I am behind corporate proxy but the proxy vars are setup already. This was working few weeks ago though.

### ISSUE THREAD

**Issue by harnoor-ai-cloud** [microsoft/vscode-azureresourcegroups#920]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureResourceGroups.logIn
Error type: Error
Error Message: Network failure

Version: 0.9.4
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.93.0
Language: en

<details>
<summary>Call Stack</summary>

```
p.fetchTokenResponse extension.js:2:259168
p.exchangeCodeForSession extension.js:2:257924
p.createSessionWithLocalServer extension.js:2:249185
extension.js:2:248009extension.js:2:248009
```

</details>

**Comment by alexweininger** [comment]
Could you retry sign in with the following setting enabled?

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/06ae79f7-3740-47ec-8d75-31b84e1ef044">
