### ISSUE TITLE
Cannot log in with proper account in VS code extension

### ISSUE THREAD

**Issue by onefox-dev** [microsoft/vscode-azureresourcegroups#929]
The Azure extension prompts me to login, yet it only allows me to login on my private account, not any other (work) accounts. Even those I'm already logged in to in VS Code. Manually pasting in the proper Tenant ID doesn't work either. 

![image](https://github.com/microsoft/vscode-azureresourcegroups/assets/131253346/f0f812ac-4880-4987-8141-dfea3308c206)

**Comment by alexweininger** [comment]
Hi @onefox-dev, make sure you are logged in to the correct account. To do so, check the built-in VS Code Accounts menu.

<img width="581" alt="image" src="https://github.com/user-attachments/assets/7d11bdea-ed94-4eee-ac89-47c74c405ee9">
