### ISSUE TITLE
The install toast about "GitHub Copilot for Azure extension" disappears after clicking the "Learn More" button

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#951]
**OS:** All
**Build Version:** 20241101.1
**Regression:** Not a regression

**Repro Steps:**
1. Install "GitHub Copilot" & "GitHub Copilot Chat" extensions in VS Code.
2. Install "Azure Resources" extension.
3. Navigate to Azure view, the below install toast about "GitHub Copilot for Azure extension" appears.
![Image](https://github.com/user-attachments/assets/3f8295fb-d4fc-41e1-9b14-6b06d0a2c954)
4. Click the "Learn More" button.
5. Check whether the install toast still exists after clicking the "Learn More" button.

**Expect:**
The install toast still exists after clicking the "Learn More" button.

**Actual:**
The install toast disappears after clicking the "Learn More" button.

**Comment by jinglouMSFT** [comment]
I would expect it to close the toast notification but we should take the user to the GHCP4Azure install page on VS Code Marketplace where the user could learn about the extension and decide to install it or not to install it.  Do we bring the user to the marketplace?

**Comment by alexweininger** [comment]
Closing as this is expected behavior.
