### ISSUE TITLE
An error "Cannot read properties of undefined (reading 'tenantId')" occurs when executing the "Azure: Sign in to Tenant" command

### ISSUE THREAD

**Issue by v-meilei** [microsoft/vscode-azureresourcegroups#966]
**OS:** All
**Build Version:** v0.9.9
**Regression:** Not a Regression

**Repro Steps:**

1. F1 -> Select "Azure: Sign in to Tenant".
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![Image](https://github.com/user-attachments/assets/a924dc3f-91be-445f-9126-3cece2af9e08)

**Comment by motm32** [comment]
Thanks for filing this issue! I am unable to repro this issue is it still occuring?

**Comment by motm32** [comment]
@v-meilei Thank you I will take a look into it. One question I have is does this error reproduce if authenticating a tenant from the tenant view? Such as checking an unauthenticated tenant?

**Comment by v-meilei** [comment]
@motm32 Hi Megan,
1. This error occurs immediately after running the command, 
2. If unchecking an unauthenticated tenant from the tenant view, this error does not reproduce when clicking the "Sign in to Tenant" button.
