### ISSUE TITLE
An error occurs when expanding 2 identical subscription nodes logged in with 2 different Microsoft accounts (resources grouped by "Resource Group")

### ISSUE THREAD

**Issue by v-meilei** [microsoft/vscode-azureresourcegroups#972]
**OS:** Win 11
**Build Version**: 20241205.1

**Repro Steps:**

1. Sign in with 2 different Microsoft accounts and select the same subscriptions.
    ![Image](https://github.com/user-attachments/assets/fb24ab13-4dea-404a-8298-36dee232f2a0)
2. Group the resources by "Resource Group".
3. Expand one of the subscription nodes -> Expand the second subscription node with a different account.
4. Check whether the second subscription node shows well.

**Expect:**
The second subscription node shows well.

**Actual:**
An error occurs and the second subscription is empty.
![Image](https://github.com/user-attachments/assets/77710eba-d88b-4805-ab0f-40fa721062e3)

**More Info:**
1. This issue does not reproduce if group by "Resource Type"/"Location"/"ARM Tag".
2. This issue does not reproduce when expanding 2 different subscription nodes logged in with 1 Microsoft account.

**Comment by Amar-QA** [comment]
This issue also reproduces when expanding the resource group node that contains resources under **Focused Resources**.

![Image](https://github.com/user-attachments/assets/e97bb6a4-ef3d-4294-bff4-2981a63b3a37)
![Image](https://github.com/user-attachments/assets/3d940a84-41ce-4460-a20b-9f4152aeac9e)

**Comment by v-meilei** [comment]
1. This issue also reproduces when expanding an extension node that contains resources under "focused resources". (resources grouped by "Resource Type")
2. This issue also reproduces when expanding a location node that contains resources under "focused resources". 
(resources grouped by "Location")
