### ISSUE TITLE
There is no command "Azure: Add Account" in the "Command Palette"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#995]
**OS:** All
**Build Version:** 0.9.9
**Regression:** Not a regression

**Repro Steps:**
1. Navigate to "Accounts & Tenants" view, there is an icon "Add Account".
2. Open the "Command Palette".
3. Check whether there is a command "Azure: Add Account" in the "Command Palette".

**Expect:**
There is a command "Azure: Add Account" in the "Command Palette".

**Actual:**
There is no command "Azure: Add Account" in the "Command Palette".

**Comment by motm32** [comment]
Thanks for filing this issue. There already is an existing "Azure: Sign in" in the command palette which allows users to sign in to another account through that command by selecting "Sign in to another account" on the drop down: ![Image](https://github.com/user-attachments/assets/7881445b-fc61-4603-8498-c755704fe22f)

At the moment I don't think it makes sense to have both commands appear in the command palette but we can revisit that in the future if users report this as an issue.

**Comment by alexweininger** [comment]
I'm fine either way
